---
title: "volcanic range"
author: "Rebecca Hoyd"
date: "11/30/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggplot2)
library(ggrepel)
```

```{r}
load("../../exploratory/data/plotdat_mouse-exp_vulcanrange.rda")
mickey <- readRDS("../../exploratory/data/microbes_found-in-tissues.rds") 

write.csv(rangedat.form, "../tables/supplementary_volcanicrange-data.csv", row.names = F)
```

# Proteobacteria shaped

```{r}

rangedat.form %>%
  ggplot(aes(x = patval, y = -log(p.value), shape =  protval)) +
  geom_point(aes(size = sizeval, fill =direction)) +
  geom_label_repel(aes(label = pointlab), size = 3) +
  scale_fill_brewer(palette = "Set1", name = "", labels = c("Depleted\nin Obese", "Enriched\nin Obese")) +
  scale_x_continuous(breaks = patkey$patnum, labels = patkey$patient) +
  scale_shape_manual(values = 21:22,
                     name = "",
                     breaks = c("Proteobacteria", "Not Proteobacteria"),
                     labels = c("Proteobacteria", "Others")) +
  scale_size_manual(breaks = c("a", "b", "c"), 
                    values = c(1,2,3), 
                    labels = c("<1", "<2", ">=2"),
                    name = "FoldChange") +
  labs(x = "Patient") +
  guides(fill = guide_legend(override.aes=list(shape=21))) +
  theme_bw() +
  theme(text = element_text(size = 8))
ggsave("../figures/volcanic-range_mouseexp_legend.png", height = 4, width = 3)

rangedat.form2 %>%
  ggplot(aes(x = patval, y = -log(p.value), shape = protval)) +
  geom_point(aes(size = sizeval, fill =direction), show.legend = F) +
  geom_label_repel(aes(label = pointlab), size = 2, show.legend = F) +
  scale_fill_brewer(palette = "Set1", name = "", labels = c("Depleted\nin Obese", "Enriched\nin Obese")) +
  scale_x_continuous(breaks = patkey$patnum, labels = patkey$patient) +
  scale_shape_manual(values = 21:22,
                     name = "",
                     breaks = c("Proteobacteria", "Not Proteobacteria"),
                     labels = c("Proteobacteria", "Others")) +
  scale_size_manual(breaks = c("a", "b", "c"), 
                    values = c(1,2,3), 
                    labels = c("<1", "<2", ">=2"),
                    name = "FoldChange") +
  labs(x = "Patient") +
  theme_bw() +
  theme(text = element_text(size = 8))
ggsave("../figures/volcanic-range_mouseexp.png", height = 3.5, width = 3.5)
ggsave("../figures/volcanic-range_mouseexp.svg", height = 3.5, width = 3.5)
```

# Tissue source shaped

```{r}
colnames(mickey)[1] <- "term"
rangedat.form2 <- rangedat.form %>%
  drop_na(direction) %>%
  left_join(mickey) %>%
  mutate(tissue = replace_na(tissue, "Other"))


rangedat.form2 %>%
  ggplot(aes(x = patval, y = -log(p.value), shape = tissue)) +
  geom_point(aes(size = sizeval, fill =direction)) +
  geom_label_repel(aes(label = pointlab), size = 3) +
  scale_fill_brewer(palette = "Set1", name = "", labels = c("Depleted\nin Obese", "Enriched\nin Obese")) +
  scale_x_continuous(breaks = patkey$patnum, labels = patkey$patient) +
  # scale_shape(name = "",
  #             breaks = c("Proteobacteria", "Not Proteobacteria"), 
  #             labels = c("Proteobacteria", "Others")) +
  scale_shape_manual(values = 21:24) +
  scale_size_manual(breaks = c("a", "b", "c"), 
                    values = c(1,2,3), 
                    labels = c("<1", "<2", ">=2"),
                    name = "FoldChange") +
  labs(x = "Patient") +
  theme_bw() +
  theme(text = element_text(size = 8))
ggsave("../figures/volcanic-range_mouseexp_legend_tissue.png", height = 4, width = 3)

rangedat.form2 %>%
  ggplot(aes(x = patval, y = -log(p.value), shape = tissue)) +
  geom_point(aes(size = sizeval, fill =direction), show.legend = F) +
  geom_label_repel(aes(label = pointlab), size = 2, show.legend = F) +
  scale_fill_brewer(palette = "Set1", name = "", labels = c("Depleted\nin Obese", "Enriched\nin Obese")) +
  scale_x_continuous(breaks = patkey$patnum, labels = patkey$patient) +
  # scale_shape(name = "",
  #             breaks = c("Proteobacteria", "Not Proteobacteria"), 
  #             labels = c("Proteobacteria", "Others")) +
  scale_shape_manual(values = 21:24) +
  scale_size_manual(breaks = c("a", "b", "c"), 
                    values = c(1,2,3), 
                    labels = c("<1", "<2", ">=2"),
                    name = "FoldChange") +
  labs(x = "Patient") +
  theme_bw() +
  theme(text = element_text(size = 8))
ggsave("../figures/volcanic-range_mouseexp_tissue.png", height = 3.5, width = 3.5)
ggsave("../figures/volcanic-range_mouseexp_tissue.svg", height = 3.5, width = 3.5)
```

