---
title: "TCGA extra"
output: html_document
---

```{r setup, include=FALSE}
library(readr)
library(tibble)
library(dplyr)
library(tidyr)
library(ggplot2)
```


```{r cars}
#load files to match id
TCGA_id_link <- read_csv("../data/TCGA-link-bam-and-expression-files.csv")
TCGA.COAD_id <- read.delim("../data/gdc_manifest.2020-05-28.txt")
TCGA.READ_id <- read.delim("../data/gdc_manifest.2020-05-28 _READ.txt")
## add cancer type to the data frame
TCGA.COAD_id <- data.frame(TCGA.COAD_id$id, rep("COAD", length(TCGA.COAD_id$id)))
TCGA.READ_id <- data.frame(TCGA.READ_id$id, rep("READ", length(TCGA.READ_id$id)))
colnames(TCGA.COAD_id) <- c("file_id.BAM", "Tissue")
colnames(TCGA.READ_id) <- c("file_id.BAM", "Tissue")
TCGA_tissue_id <- rbind(TCGA.COAD_id, TCGA.READ_id)
# load cibersortx file
TCGA_CUS <- read.csv("../data/CIBERSORT/CIBERSORTx-deconvolved/COAD-READ_cus.csv", header = TRUE)
TCGA_LM <- read.csv("../data/CIBERSORT/CIBERSORTx-deconvolved/COAD-READ_lm.csv", header = TRUE)
BRCA_C <- read.csv("../data/CIBERSORT/CIBERSORTx-deconvolved/BRCA_CUS.csv", header = TRUE)%>%
  mutate(Cancer = "BRCA")
SARC_C <- read.csv("../data/CIBERSORT/CIBERSORTx-deconvolved/SARC_CUS.csv", header = TRUE)%>%
  mutate(Cancer = "SARC")
LUSC_C <- read.csv("../data/CIBERSORT/CIBERSORTx-deconvolved/LUSC_CUS.csv", header = TRUE)%>%
  mutate(Cancer = "LUSC")
LUAD_C <- read.csv("../data/CIBERSORT/CIBERSORTx-deconvolved/LUAD_CUS.csv", header = TRUE)%>%
  mutate(Cancer = "LUAD")
BRCA_L <- read.csv("../data/CIBERSORT/CIBERSORTx-deconvolved/BRCA_LM22.csv", header = TRUE)%>%
  mutate(Cancer = "BRCA")
SARC_L <- read.csv("../data/CIBERSORT/CIBERSORTx-deconvolved/SARC_LM22.csv", header = TRUE)%>%
  mutate(Cancer = "SARC")
LUSC_L <- read.csv("../data/CIBERSORT/CIBERSORTx-deconvolved/LUSC_LM22.csv", header = TRUE)%>%
  mutate(Cancer = "LUSC")
LUAD_L <- read.csv("../data/CIBERSORT/CIBERSORTx-deconvolved/LUAD_LM22.csv", header = TRUE)%>%
  mutate(Cancer = "LUAD")
KIRC_C <- read.csv("../data/CIBERSORT/CIBERSORTx-deconvolved/KIRC_CUS.csv", header = TRUE)%>%
  mutate(Cancer = "KIRC")
KIRC_L <- read.csv("../data/CIBERSORT/CIBERSORTx-deconvolved/KIRC_LM22.csv", header = TRUE)%>%
  mutate(Cancer = "KIRC")

##combine tissue and deconvolved CUS
TCGA_tissue_id <- left_join(TCGA_id_link, TCGA_tissue_id)
colnames(TCGA_tissue_id) <- c("file_id.BAM","Mixture","Cancer")
TCGA_CUS <- left_join(TCGA_CUS, TCGA_tissue_id)
TCGA_CUS <- TCGA_CUS %>% select(Cancer, everything())

##combine tissue and deconvolved LM
TCGA_LM <- left_join(TCGA_LM, TCGA_tissue_id)
TCGA_LM <- TCGA_LM %>% select(Cancer, everything())
TCGA_CUS <- bind_rows(TCGA_CUS,SARC_C,LUAD_C,LUSC_C,KIRC_C,BRCA_C)%>%
  dplyr::select(Mixture, Cancer, V.neutrophil, Blood.neutrophil)
TCGA_LM <- bind_rows(TCGA_LM,SARC_L,LUAD_L,LUSC_L,KIRC_L, BRCA_L)%>%
  dplyr::select(Mixture, Cancer, Neutrophils)

##combine vat and neut
TCGA_dat <- TCGA_LM %>%
  left_join(TCGA_CUS)%>%
  rename("VAT_Neut" = "V.neutrophil", "Blood_Neut" = "Neutrophils", "C.B" = "Blood.neutrophil", "Tissue" = "Cancer") %>%
  mutate(file_name.expression = paste0(Mixture,".FPKM.txt.gz"))
dat_plot <- TCGA_dat %>% 
  gather("cell_type", "relative_abundance", 3:5) %>%
  mutate(Tissue2nd = paste0(Tissue, cell_type)) %>%
  filter(!cell_type == "C.B")
```

#order by VAT sum
```{r}
tiskey <- unique(select(TCGA_dat, Tissue))
tiskey$sum_VAT <- sapply (1:nrow(tiskey), function(i) sum(TCGA_dat$VAT_Neut[which(tiskey$Tissue[i] == TCGA_dat$Tissue)]))
tiskey$sum_blood <- sapply (1:nrow(tiskey), function(i) sum(TCGA_dat$Blood_Neut[which(tiskey$Tissue[i] == TCGA_dat$Tissue)]))
tiskey$type <- tiskey$sum_VAT > tiskey$sum_blood
colnames(tiskey) <- c("Tissue", "sum_VAT","sum_blood","type")
```



##assign y reference value to each sample for background fill
```{r}
#reorder the level of dat_plot$Tissue to change the y axis (change based on which order y axis should be)
#levels(dat_plot$Tissue2nd) <- c(unique(pv$Tissue2nd))
#dat_plot$Tissue2nd <- factor(dat_plot$Tissue2nd, levels = pvv$Tissue2nd)
#dat_plot$protocol <- factor(dat_plot$protocol, levels = pv$protocol)

d.plot <- dat_plot %>%
  ###filter to only COAD
  filter(Tissue == "COAD")%>%
  mutate(patnum = as.numeric(as.factor(Tissue)))
numpatkey <- select(d.plot,Tissue, patnum)
numpatkey <- numpatkey[!duplicated(numpatkey),]
numpatkey <- left_join(numpatkey, tiskey)
numpatkey$type[which(numpatkey$type == "TRUE")] <- "VAT_Neut"
numpatkey$type[which(numpatkey$type == "FALSE")] <- "Blood_Neut"

numpatkey <- numpatkey %>%
  mutate(ylow = patnum - .45,
         yhigh = patnum + .45,
         xmin = 0,
         xmax = 0.75
  ) %>%
  gather(xmin, xmax, key = "end", value = "x")
#numpatkey$Tissue <- factor(numpatkey$protocol, levels = pv$protocol)
#numpatkey <- numpatkey[order(numpatkey$yhigh),]
```



```{r}
##annotation pv
ggplot()+
  geom_rect(data = numpatkey, mapping = aes(xmin = ylow, xmax = yhigh, ymin = 0, ymax = 0.6, fill=type), inherit.aes = F,show.legend = F, alpha = 0.3)+
  geom_boxplot(data = d.plot, aes(x = as.factor(patnum), y = relative_abundance, fill = cell_type), inherit.aes = F, show.legend = T)+
  scale_x_discrete(breaks = unique(numpatkey$patnum), labels = unique(numpatkey$Tissue))+
  theme(axis.text.x = element_text(size=10, angle=0))+
  theme_bw()+
  scale_fill_manual(values=c("tomato","gold"), breaks = c("Blood_Neut","VAT_Neut"), name = "neutrophil type")+
  xlab("Tissue")+
  ylab("Relative Abundance")+
  coord_flip()+
  ggsave("../figures/COAD_VAT.png")
```




```{r}
library(survminer)
library(survival)
##combine clinical data
BRCA_CLI <- read.csv("../data/survival info/BRCA_CLI.csv", header = TRUE)
LUAD_CLI <- read.csv("../data/survival info/LUAD_CLI.csv", header = TRUE)
LUSC_CLI <- read.csv("../data/survival info/LUSC_CLI.csv", header = TRUE)
SARC_CLI <- read.csv("../data/survival info/SARC_CLI.csv", header = TRUE)
COAD_CLI <- read.csv("../data/survival info/COAD_CLI.csv", header = TRUE)
READ_CLI <- read.csv("../data/survival info/READ_CLI.csv", header = TRUE)
KIRC_CLI <- read.csv("../data/survival info/KIRC_CLI.csv", header = TRUE)
ALL_CLI <- bind_rows(LUAD_CLI,LUSC_CLI,READ_CLI,COAD_CLI,KIRC_CLI,SARC_CLI,BRCA_CLI)%>%
  select(file_id.BAM, days_to_last_follow_up,days_to_death,vital_status)%>%
  mutate(vital_status = ifelse(vital_status=="Alive",0,1),
         days = ifelse(is.na(days_to_death),days_to_last_follow_up,days_to_death))

## combine manifest files
BRCA_MAN <- read.csv("../data/survival info/BRCA_MAN.csv", header = TRUE)
LUAD_MAN <- read.csv("../data/survival info/LUAD_MAN.csv", header = TRUE)
LUSC_MAN <- read.csv("../data/survival info/LUSC_MAN.csv", header = TRUE)
SARC_MAN <- read.csv("../data/survival info/SARC_MAN.csv", header = TRUE)
COAD_MAN <- read.csv("../data/survival info/COAD_MAN.csv", header = TRUE)
READ_MAN <- read.csv("../data/survival info/READ_MAN.csv", header = TRUE)
KIRC_MAN <- read.csv("../data/survival info/KIRC_MAN.csv", header = TRUE)
ALL_MAN <- bind_rows(LUAD_MAN,LUSC_MAN,COAD_MAN,KIRC_MAN,SARC_MAN,READ_MAN,BRCA_MAN) %>%
  select(file_name.expression,file_id.BAM,file_id.expression)%>%
  rename("Mixture" = "file_id.expression")

##prepare survival data
SURV_CR <- TCGA_dat %>%
  filter(Tissue %in% c("COAD","READ"))%>%
  left_join(ALL_MAN, by = "file_name.expression")%>%
  left_join(ALL_CLI)%>%
  select(file_id.BAM,days,vital_status,Tissue,VAT_Neut,Blood_Neut)
SURV_REST <- TCGA_dat %>%
  filter(!Tissue %in% c("COAD","READ"))%>%
  left_join(ALL_MAN, by = "Mixture")%>%
  left_join(ALL_CLI)%>%
  select(file_id.BAM,days,vital_status,Tissue,VAT_Neut,Blood_Neut)
SURV_dat <- bind_rows(SURV_CR,SURV_REST)

## plot using facet wrap
SURV_d <- SURV_dat %>%
  mutate(VAT_type = ifelse(VAT_Neut > sort(VAT_Neut)[0.9*length(VAT_Neut)],"More VAT","less VAT"),
         Blood_type = ifelse(Blood_Neut > sort(Blood_Neut)[0.9*length(Blood_Neut)],"More Blood_n","less Blood_n"))%>%
  ### filter to only COAD
  filter(Tissue == "COAD")

surv_plot_VAT <- survfit(Surv(days, vital_status) ~ VAT_type, data = SURV_d)
surv_plot_Blo <- survfit(Surv(days, vital_status) ~ Blood_type, data = SURV_d)
ggsurvplot_facet(surv_plot_Blo, SURV_d, facet.by = "Tissue", scales = "free_x") +
  theme_bw()+
  ggsave("../figures/COAD_surv_Blo.png")
ggsurvplot_facet(surv_plot_VAT, SURV_d, facet.by = "Tissue", scales = "free_x") +
  theme_bw()+
  ggsave("../figures/COAD_surv_VAT.png")
```

```{r}
library(broom)
cancers <- unique(SURV_dat$Tissue)
percentiles<- seq(0.01,0.99,0.01)
## creating a dataframe for saving the p values ##
ptable <- list()
percents.list <- list()
canc.list <- list()
for(e in cancers){
  ##create subset for each cancer 
  canc_set <- SURV_dat[SURV_dat$Tissue== e,]
  for (p in percentiles) {  ## loop through every percentile
    #find the threshold based on the percentile
    cut <- quantile(canc_set$VAT_Neut, p)
    canc_set$type <- ifelse(canc_set$VAT_Neut > cut, 1, 0)
    survtemp <- coxph(Surv(days, vital_status) ~ type, canc_set)
    ##put wanted value in dataframe format
    dat_temp <- merge(data.frame(summary(survtemp)[["conf.int"]]), data.frame(summary(survtemp)[["coefficients"]]))
    ## extract value from dataframe
    ptable[[e]] <- dat_temp %>%
      mutate(hazard.ratio = exp..coef.,
        low.bound = lower..95,
        upper.bound = upper..95,
        pval = log(Pr...z..),
        percentiles = p,
        cancer = e) %>%
      select(hazard.ratio, low.bound, upper.bound, percentiles, pval, cancer)
    percents.list[[as.character(p)]] <- ptable
    ptable <- list()
  }
  canc.list[[e]] <- bind_rows(lapply(percents.list, function(x) bind_rows(x)))
  percents.list <- list()
}
## decide whether the line goes up or down
canc.df <- bind_rows(canc.list) %>%
  mutate(dir = ifelse(hazard.ratio >= 1, "neg", "pos"))%>%
  filter(cancer == "COAD")

ggplot(canc.df, aes(x=percentiles, y=pval))+
  geom_line(aes(color = dir, group=1))+
  geom_hline(yintercept = log(0.05))+
  ylab("log(pval)")+
  facet_wrap(~cancer, scales = "free_y")+
  theme_bw()+
  ggsave("../figures/hoyd_COAD.png", height = 10, width = 15)

```

```{r}
clinical <- read.csv("C:/Users/Leste/Box/atneusig/data/clinical.csv")
relative_abundance <- read.csv("C:/Users/Leste/Box/atneusig/data/relative_abundance.csv")
gram_neg_list <- read.csv("../data/gram negative list.csv")%>%
  mutate(gram.negative = trimws(gram.negative, which = c("both")))
g <- gram_neg_list$gram.negative
id <- select(clinical, sample.microbe,sample.expression)%>%
  rename("Mixture"="sample.expression","sample"="sample.microbe")
TCGA_id <- TCGA_id_link %>%
  rename("Mixture"="file_id.expression", "sample"="file_id.BAM")%>%
  rbind(id)
  

micro <- relative_abundance %>%
  mutate(gg = gsub("g__(.*)(-s.*)","\\1",genus),
         gg = gsub("g__(.*)","\\1",gg))%>%
  filter(gg %in% g)%>%
  select(sample, exo.ra, microbe)%>%
  spread(microbe, exo.ra)%>%
  mutate(sum.ra = rowSums(.[,-1]))%>%
  select(sample, sum.ra)

neut <- TCGA_id %>%
  left_join(dat_plot)%>%
  left_join(micro)%>%
 # select(-Tissue2nd,-patnum,-file_name.expression) %>%
  filter(!cell_type == "C.B",
         !is.na(sum.ra),
         ###filter to only COAD
         Tissue == "COAD") %>%
  select(sample)

ggplot(neut,aes(x=sum.ra, y=relative_abundance,color=cell_type))+
  geom_point()+
  geom_smooth(method = "lm")+
  facet_wrap(~Tissue, scales = "free")+
  theme_bw()+
  theme(axis.text.x = element_text(size = 7))+
  ylab("Neutrophil relative abundance")+
  xlab("Gram negative microbs relative abundance")+
  ggsave("../figures/COAD.micro_neut.png")
  
```


subsection of COAD
```{r}
relative_abundance <- read.csv("C:/Users/Leste/Documents/GitHub/exotcc/atneusig/data/ra_COAD.csv")
ra_COAD <- relative_abundance %>%
  select(sample, exo.ra, microbe, genus)
  
write.csv(ra_COAD,"C:/Users/Leste/Documents/GitHub/exotcc/atneusig/data/ra_COAD.csv")
```
