---
title: "SCRNA Visualizations"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(Seurat)
# library(dplyr)
# library(ggforce)
# library(viridis)
# library(tmesig)
```

# Load data

"scrna" is the seurat object from the paper: https://www.nature.com/articles/s41597-023-02074-6. It is also available as source data.

```{r}
scrna <- readRDS("/fs/ess/PAS1695/projects/atbac/data/scRNA/refquery_final.rds")
```

# Initial formatting to get scrna neutrophils
```{r} 
counts <- as.matrix(GetAssayData(object = scrna, slot = "counts")) %>%
  t() %>%
  as.data.frame()

cell.type <- FetchData(object = scrna, vars = "Cell_Cluster_level2") %>%
  as.data.frame() %>%
  rename("Cell Type" = "Cell_Cluster_level2")

umap <- as.data.frame(Embeddings(object = scrna, reduction = "umap")) 
```

```{r}
scrna.subset <- cbind(counts, cell.type, umap) %>%
  rownames_to_column(var = "Sample") %>%
  filter(`Cell Type` == "Neutrophils")

saveRDS(scrna.subset, "../data/scrna-neutrophils.rds")
```
