---
title: "Figure 2"
author: "Rebecca Hoyd"
date: "3/19/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(RColorBrewer)
library(ggrepel)
```


# Drake targets

```{r}
loadd(samples.bmi.firmicutes)
loadd(taxcounts.nocontam.phyl)
loadd(sourceres)
loadd(bacteria.desres)
```

# Addt. sample order label

```{r}
samples.bmi.firmicutes %>%
  mutate(count = 1) %>%
  ggplot(aes(x=0, y = count, fill = BMI)) +
  geom_col(position = "fill") +
  scale_fill_manual(breaks = c("Lean", "Obese"), values = c("grey", "black")) +
  coord_flip() +
  theme_void() 
  # ggsave("../figures/BMI-labels-for-ordered-stack.pdf", width = 10, height = 1)
```

# Stacked bar: Phyla level bacteria

```{r}
getPalette <- colorRampPalette(brewer.pal(11, "Spectral"))
phyls <- unique(as.character(taxcounts.nocontam.phyl$Phylum))
use.palette <- getPalette(14)
use.palette[13] <- "grey"

taxcounts.nocontam.phyl %>%
  filter(sample != "ABNEG") %>%
  # mutate(seqtype = ifelse(grepl("-C", sample), "RNA", "DNA")) %>%
  # filter(seqtype == "DNA" & !grepl("ABNEG", sample) & grepl("-I", sample)) %>%
  # left_join(getsampord) %>%
  ggplot(aes(x = fct_relevel(sample, rev(samples.bmi.firmicutes$sample)), 
             y = count, 
             fill = fct_relevel(Phylum, "Firmicutes"))) +
  geom_col(position = "fill") +
  scale_fill_manual(breaks = phyls, values = use.palette, name = "Phylum") + 
  labs(x = "", y = "") +
  theme_bw() +
  theme(axis.text.x = element_blank()) +
  ggsave("../../figures/stacked-bar_phyla_DNA-ordered_nocontam.pdf",
         height = 4,
         width = 6) +
    ggsave("../../figures/stacked-bar_phyla_DNA-ordered_nocontam.png",
         height = 4,
         width = 7)
```

# Stacked bar: Sourcetracker results

```{r}
sourceres  %>%
  gather(!SampleID, key = "Source", value = "prop") %>%
  mutate(Source = ifelse(Source == "Unknown", "Other", Source)) %>%
  mutate(Source = gsub("\\.", " ", Source)) %>%
  # filter(source != "Other") %>%
  ggplot(aes(x = fct_relevel(SampleID, rev(samples.bmi.firmicutes$sample)), 
             y = prop, 
             fill = Source)) +
  geom_col(position = "fill") +
  scale_fill_brewer(palette = "Dark2", na.value = "grey50") +
  labs(x = "", y = "") +
  theme_bw() +
  theme(axis.text.x = element_blank()) +
  ggsave("../../figures/stacked-bar_sourcetracker.pdf",
         height = 4,
         width = 6) +
  ggsave("../../figures/stacked-bar_sourcetracker.png",
         height = 4,
         width = 7)
```

# DESeq results volcano plot

```{r}
bacteria.desres %>%
  mutate(colgroup = ifelse(pvalue < 0.1, Taxa.Level, NA)) %>%
  ggplot(aes(x = log2FoldChange, y = -log(pvalue), color = colgroup)) +
  geom_point() +
  geom_text_repel(aes(label = ifelse(!is.na(colgroup), Taxa, NA)), 
                  show.legend = FALSE) +
  geom_hline(yintercept = -log(.1), linetype = "dashed") +
  geom_vline(xintercept = -2, linetype = "dashed") +
  geom_vline(xintercept = 2, linetype = "dashed") +
  scale_color_brewer(palette = "Dark2", na.value = "grey50", name = "Taxonomy Level") +
  theme_bw(base_size = 10) 
  # theme(legend.position = c(0.15, 0.2),
  #       legend.box.background = element_rect(color = "black"))
  ggsave("../../figures/volcano_deseq2-DNA-results.pdf") 
  ggsave("../../figures/volcano_deseq2-DNA-results.png",
         height = 2, width = 7, dpi = 300)
```
