---
title: "Figure 3"
author: "Rebecca Hoyd"
date: "3/8/2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggrepel)
```


# B: Boxplots of absolute abundance of microbes within mouse tissues

```{r}
load("prepared-data/mouse_tissuebox.rda")
zymo.tissuedat %>%
  filter(source == "tissue") %>%
  mutate(dietdummy = ifelse(tissue_type == "VAT", Diet, "HFD")) %>%
  ggplot(aes(x = Gavage, y = log(`genome_copies_per_ul*`))) +
  facet_wrap(vars(tissue_type), nrow = 1, strip.position = "bottom") +
  geom_boxplot(aes(fill = Gavage, color = dietdummy), 
               outlier.shape = NA
               ) +
  geom_point(aes(shape = Diet, 
                 fill = Gavage,
                 group = dietdummy), 
             size = 3,
             color = "grey30",
             position = position_jitterdodge(jitter.width = .1)
             ) +
  
  theme_bw(base_size = 10) +
  scale_fill_manual(breaks = c("Lean", "Obese", "Saline"),
                    values = c("#A76686","#94BBC6","#FEFE7D"),
                    aesthetics = c( "fill")) +
  scale_shape_manual(breaks = c("Chow", 
                                "HFD"),
                     values = c(21,
                                24)
                     ) +
  scale_color_manual(values = c("grey25", "grey30")) +
  labs(x = "",
       y = "Log(Microbe Genome Copies per ul)") +
  guides(shape = guide_legend(override.aes = list(fill = "black")),
         fill = guide_legend(override.aes = list(shape = NA)),
         color = F) +
  theme_bw() +
  theme(axis.ticks.x = element_blank(),
        axis.text.x = element_blank())

ggsave("../figures/zymo_abs-abundance_tissues.png",
     height = 4, width = 6)
```

# F: Volcano original mouse experiment

```{r}
load("prepared-data/zymo-old.rda")
```

```{r}
volplot.form <- volplot %>%
  mutate(textlab_trunc = gsub("\\w__(.*)", "\\1", textlab),
         textlab_trunc_red = if_else(grepl(".*ales$|.*aceae$", textlab_trunc),
                                     true = NA_character_,
                                     if_else(grepl("Parab", textlab_trunc),
                                     true = "Paraburkholderia insula",
                                     false = textlab_trunc)),
         textlab_plotmath = ifelse(taxlev %in% c("g", "s"), paste0("italic(", gsub(" ", "~", textlab_trunc_red), ")"), textlab_trunc_red)
         ) %>%
  mutate(Taxonomy = if_else(grepl("c", taxlev),
                               true = "Class",
                               false = if_else(grepl("f", taxlev),
                               true = "Family",
                               false = if_else(grepl("g", taxlev),
                               true = "Genus",
                               false = if_else(grepl("o", taxlev),
                               true = "Order",
                               false = if_else(grepl("s", taxlev),
                               true = "Species",
                               false = taxlev)))))) %>%
  mutate(Taxonomy = fct_relevel(Taxonomy, c("Species", "Genus", "Family", "Order", "Class"))) %>%
  filter(!inf.rescale %in% c(-10,10) & !is.na(inf.rescale)) %>%
  filter(!term %in% c("f__NA", "g__NA"))

volplot.form %>%
  ggplot(aes(x = inf.rescale, y = -log(p.value))) +
  geom_vline(xintercept = 2, lty = 2, color = "grey50") +
  geom_vline(xintercept = -2, lty = 2, color = "grey50") +
  geom_hline(yintercept = -log(0.05), lty = 2, color = "grey50") +
  geom_point(aes(color = Taxonomy)) +
  geom_text_repel(aes(label = textlab_plotmath), size = 2.5,
                  show.legend = FALSE,
                  parse = T) +
  labs(x = "log(fold change, base=2)", y = "-log(p value)") +
  scale_color_brewer(palette = "Dark2", na.value = "grey") +
  # xlim(c(-10,10)) +
  theme_bw(base_size = 8) +
  theme(axis.title = element_text(family = "Times New Roman"))
ggsave("../../figures/volcano_HFD_Obese-Lean_VAT.png",
       height = 2.25, width = 4)
```

## related table

```{r}
write.csv(micmeans, "../../tables/HFD-stool_pvals_VAT.csv", row.names = F)
```

# G: Volcanic range new mouse experiments

## Proteobacteria shape

```{r}
load("prepared-data/mouse_vulc-range.rda")
vulcrange$rangedat.form %>%
  ggplot(aes(x = patval, y = -log(p.value), shape =  protval)) +
  geom_point(aes(size = sizeval, fill =direction)) +
  geom_label_repel(aes(label = pointlab), size = 3) +
  scale_fill_brewer(palette = "Set1", name = "", labels = c("Depleted\nin Obese", "Enriched\nin Obese")) +
  scale_x_continuous(breaks = vulcrange$patkey$patnum, labels = vulcrange$patkey$patient) +
  scale_shape_manual(values = 21:22,
                     name = "",
                     breaks = c("Proteobacteria", "Not Proteobacteria"),
                     labels = c("Proteobacteria", "Others")) +
  scale_size_manual(breaks = c("a", "b", "c"), 
                    values = c(1,2,3), 
                    labels = c("<1", "<2", ">=2"),
                    name = "FoldChange") +
  labs(x = "Patient") +
  guides(fill = guide_legend(override.aes=list(shape=21))) +
  theme_bw() +
  theme(text = element_text(size = 8))
ggsave("../figures/volcanic-range_mouseexp_legend.png", height = 4, width = 3)

rangedat.form %>%
  ggplot(aes(x = patval, y = -log(p.value), shape = protval)) +
  geom_point(aes(size = sizeval, fill =direction), show.legend = F) +
  geom_label_repel(aes(label = pointlab), size = 2, show.legend = F) +
  scale_fill_brewer(palette = "Set1", name = "", labels = c("Depleted\nin Obese", "Enriched\nin Obese")) +
  scale_x_continuous(breaks = patkey$patnum, labels = patkey$patient) +
  scale_shape_manual(values = 21:22,
                     name = "",
                     breaks = c("Proteobacteria", "Not Proteobacteria"),
                     labels = c("Proteobacteria", "Others")) +
  scale_size_manual(breaks = c("a", "b", "c"), 
                    values = c(1,2,3), 
                    labels = c("<1", "<2", ">=2"),
                    name = "FoldChange") +
  labs(x = "Patient") +
  theme_bw() +
  theme(text = element_text(size = 8))
ggsave("../../figures/volcanic-range_mouseexp.png", height = 3.5, width = 3.5)
ggsave("../../figures/volcanic-range_mouseexp.svg", height = 3.5, width = 3.5)
```

## Tissue source shape

```{r}
# colnames(mickey)[1] <- "term"
# rangedat.form2 <- rangedat.form %>%
#   drop_na(direction) %>%
#   left_join(mickey) %>%
#   mutate(tissue = replace_na(tissue, "Other"))
# 
# 
# rangedat.form2 %>%
#   ggplot(aes(x = patval, y = -log(p.value), shape = tissue)) +
#   geom_point(aes(size = sizeval, fill =direction)) +
#   geom_label_repel(aes(label = pointlab), size = 3) +
#   scale_fill_brewer(palette = "Set1", name = "", labels = c("Depleted\nin Obese", "Enriched\nin Obese")) +
#   scale_x_continuous(breaks = patkey$patnum, labels = patkey$patient) +
#   # scale_shape(name = "",
#   #             breaks = c("Proteobacteria", "Not Proteobacteria"), 
#   #             labels = c("Proteobacteria", "Others")) +
#   scale_shape_manual(values = 21:24) +
#   scale_size_manual(breaks = c("a", "b", "c"), 
#                     values = c(1,2,3), 
#                     labels = c("<1", "<2", ">=2"),
#                     name = "FoldChange") +
#   labs(x = "Patient") +
#   theme_bw() +
#   theme(text = element_text(size = 8))
# ggsave("../../figures/volcanic-range_mouseexp_legend_tissue.png", height = 4, width = 3)
# 
# rangedat.form2 %>%
#   ggplot(aes(x = patval, y = -log(p.value), shape = tissue)) +
#   geom_point(aes(size = sizeval, fill =direction), show.legend = F) +
#   geom_label_repel(aes(label = pointlab), size = 2, show.legend = F) +
#   scale_fill_brewer(palette = "Set1", name = "", labels = c("Depleted\nin Obese", "Enriched\nin Obese")) +
#   scale_x_continuous(breaks = patkey$patnum, labels = patkey$patient) +
#   # scale_shape(name = "",
#   #             breaks = c("Proteobacteria", "Not Proteobacteria"), 
#   #             labels = c("Proteobacteria", "Others")) +
#   scale_shape_manual(values = 21:24) +
#   scale_size_manual(breaks = c("a", "b", "c"), 
#                     values = c(1,2,3), 
#                     labels = c("<1", "<2", ">=2"),
#                     name = "FoldChange") +
#   labs(x = "Patient") +
#   theme_bw() +
#   theme(text = element_text(size = 8))
# ggsave("../../figures/volcanic-range_mouseexp_tissue.png", height = 3.5, width = 3.5)
# ggsave("../../figures/volcanic-range_mouseexp_tissue.svg", height = 3.5, width = 3.5)
```

