---
title: "Figure 2"
author: "Rebecca Hoyd"
date: "3/19/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(ggfortify)
library(ggforce)
library(dplyr)
# library(ggExtra)
library(ggforce)
```

# Panel A: PCA results

```{r}
load("prepared-data/pca-bldvat-exprs.rda")
pca <- 
  pca.bldvat.exprs$plotdat %>%
  mutate(combcat = gsub("\\.", ", ", combcat),
         combcat = gsub("Blood", "PBN", combcat),
         combcat = gsub("VAT", "VATN", combcat))
pca.vars <- summary(pca.bldvat.exprs$pca)$importance[2,]

p1<- ggplot(pca, aes(x = PC1, y = PC2)) +
  geom_point(aes(color = combcat), alpha = .5, show.legend = TRUE) +
  # stat_ellipse(geom = "polygon", alpha = .1, type = "norm") +
  geom_mark_ellipse(aes(fill = combcat), #label = combcat), 
                 concavity = 5,
                 expand = 0,
                 radius = 0,
                 show.legend = FALSE) +
  labs(x = paste0("PC1(", pca.vars[1]*100, "%)"),
       y = paste0("PC2(", pca.vars[2]*100, "%)"))+
  scale_color_brewer(palette="Dark2") +
  scale_fill_brewer(palette="Dark2") +
  theme_bw() +
  theme(axis.text = element_blank(), axis.ticks = element_blank(),
        legend.text = element_text(size = 10),
        legend.title = element_blank(),
        axis.title = element_text(size = 10),
        legend.position = c(0.7, 0.7),
        legend.box.background = element_rect(color = "black"))
ggMarginal(p1, groupColour = TRUE, groupFill = TRUE)
ggsave("../../figures/pca_vat-obesity_no-inset.png",
         height = 3, width = 4.5)

# p2 <- ggplot(pca, aes(x = PC1, y = PC2, color = combcat, fill = combcat, alpha = .5)) +
#   geom_point(show.legend = FALSE) +
#   # stat_ellipse(geom = "polygon", alpha = .1, type = "norm", show.legend = F) +
#   theme_bw() +
#   labs(x = "", y = "") +
#   xlim(c(-1.7e5, -1.1e5)) +
#   ylim(c(-4000, 11000)) +
#   theme(axis.text = element_blank(), axis.ticks = element_blank(),
#         legend.text = element_text(size = 10),
#         legend.title = element_blank(),
#         axis.title = element_text(size = 10)) +
#   scale_color_brewer(palette="Dark2") +
#   scale_fill_brewer(palette="Dark2")
# 
# p1 +
#   # annotation_custom(ggplotGrob(p2), 
#   #                   xmin = 4e5, xmax = 9e5, ymin = 1.5e5, ymax = 6.8e5) +
#   ggsave("../../figures/figure3/pca_vat-obesity_inset.png",
#          height = 4, width = 5)
```

# Panel B: Boxplots

```{r}
load("prepared-data/GenePath-meta.rda")

pathset1 <- c("Inflammation","Bactericidal Activity/LPS induced genes",
              "Chemotaxis"
              # "ROS production", "Inhibition of Apoptosis"
              )

GenePath.meta %>%
  drop_na(counts) %>%
  filter(Role %in% pathset1) %>%
  mutate(Role = gsub("(.*)/LPS induced genes", "\\1", Role),
         Role = gsub("ROS production", "ROS", Role),
         Role = gsub("Inhibition of Apoptosis", "Apoptosis", Role),
         Role = gsub("Growth Factors", "Growth Factor", Role)) %>%
  mutate(Role = fct_relevel(Role, "Inflammation")) %>%
  ggplot(aes(x = Gene, y = log(counts))) +
  geom_boxplot(aes(fill = source),
               show.legend = FALSE) +
  facet_row(vars(Role), scales = "free", space = "free") +
  labs(x = "", y = "") +
  theme_bw() +
  theme(text = element_text(size = 10),
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_color_brewer(palette="Dark2") +
  scale_fill_brewer(palette="Dark2") 
ggsave("../../figures/pathway-genes_boxplot_1.png", 
       height = 2, width = 5.7)

GenePath.meta %>%
  drop_na(counts) %>%
  filter(!Role %in% pathset1) %>%
  mutate(Role = gsub("(.*)/LPS induced genes", "\\1", Role),
         Role = gsub("ROS production", "ROS", Role),
         Role = gsub("Inhibition of Apoptosis", "Apoptosis", Role),
         Role = gsub("Growth Factors", "Growth Factor", Role)) %>%
  mutate(Role = fct_relevel(Role, "Inflammation")) %>%
  ggplot(aes(x = Gene, y = log(counts))) +
  geom_boxplot(aes(fill = source),
               show.legend = FALSE) +
  facet_row(vars(Role), scales = "free", space = "free") +
  labs(x = "", y = "") +
  theme_bw() +
  theme(text = element_text(size = 10),
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_color_brewer(palette="Dark2") +
  scale_fill_brewer(palette="Dark2") 
ggsave("../../figures/pathway-genes_boxplot_2.png", 
       height = 2, width = 5.7)

GenePath.meta %>%
  drop_na(counts) %>%
  filter(!Role %in% pathset1) %>%
  ggplot(aes(x = Gene, y = log(counts))) +
  geom_boxplot(aes(fill = source),
               show.legend = T) +
  facet_row(vars(Role), scales = "free", space = "free") +
  labs(x = "", y = "") +
  theme_bw() +
  theme(text = element_text(size = 10),
        axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "top") +
  scale_color_brewer(palette="Dark2") +
  scale_fill_brewer(palette="Dark2", name = "")
ggsave("../../figures/pathway-genes_boxplot_legend.png", 
       height = 2, width = 5.2)
```

# C: UpsetR with correlation colored matrix

```{r}
load("prepared-data/treatment-genepools.rda")
load("prepared-data/correlate-neut-sigs.rda")
```

```{r extensive formatting for component plots}
# Count number of shared significant genes
intersect.num <- treatment.genepools %>%
  rownames_to_column(var = "gennumid") %>%
  gather(-gennumid, key = "neutgroup", value = "sig") %>%
  group_by(gennumid) %>%
  mutate(numsig = sum(sig),
         neutgroup = gsub("Cancer", "\\.Cancer", neutgroup),
         neutgroup = gsub(" TB", "\\.TB", neutgroup)) %>%
  filter(numsig %in% 1:2 & sig == 1) %>%
  group_by(gennumid) %>%
  summarise(grouppair = paste(sort(neutgroup), collapse = "_")) %>%
  # ungroup() %>%
  add_count(grouppair) %>%
  arrange(desc(n))

# Get order of bars for upsettr
noempty.bardat <- unique(intersect.num[, c("grouppair", "n")]) %>%
  mutate(isinter = ifelse(grepl("_", grouppair), 1, 0)) %>%
  arrange(isinter, desc(n))

intersect.ord <- unique(noempty.bardat$grouppair)
empty.set.ord <- c(
  # "Endotoxin_Lung.Cancer",
                   "Active.TB_Endotoxin", "Endotoxin_Exercise", "Exercise_Sepsis", "Exercise_Synovial")

empty.bardat <- as.data.frame(cbind(grouppair = empty.set.ord, n = 0, isinter = 1),
                              stringsAsFactors = F) %>%
  mutate(n = as.numeric(n),
         isinter = as.numeric(isinter))

intersect.bardat <- bind_rows(noempty.bardat, empty.bardat) %>%
  mutate(x = row_number())

bar.ord <- intersect.bardat$grouppair

# Get order of neutrophil types for matrix plot
neutord <- colnames(treatment.genepools)
# neutord <- gsub("LungC", "Lung\\.C", neutord)
neutord <- gsub("Active ", "Active.", neutord)

# Associated matrix dots with correlation data
corr.with.col <- correlate.neut.sigs %>%
  filter(!grepl("Lung", neutrgroup1) & !grepl("Lung", neutgroup2)) %>%
  mutate(neutpair = ifelse(neutgroup2 != neutrgroup1,
                           paste(neutrgroup1, neutgroup2, sep = "_"),
                           neutrgroup1)) %>%
  select(neutrgroup1, neutgroup2, neutpair, estimate) %>%
  gather(-neutpair, -estimate, key = "groupord", value = "neutlab") %>%
  mutate(neutlab = fct_relevel(neutlab, neutord),
         neutpair = fct_relevel(neutpair, bar.ord),
         neutnum = as.numeric(neutlab)) %>%
  group_by(neutpair) %>%
  mutate(lownuet = min(neutnum),
         highneut =  max(neutnum)) %>%
  ungroup()

# Getting x and y values for the background matrix plot ribbons
neutnumkey <- corr.with.col %>%
  select(neutlab, neutnum) 
  # mutate(neutnum = as.numeric(neutlab))
neutnumkey <- neutnumkey[!duplicated(neutnumkey),]

neutnumkey <- neutnumkey %>%
  # filter(neutnum%%2 == 1) %>%
  mutate(ylow = neutnum - .5,
         yhigh = neutnum + .5,
         xmin = 0,
         xmax = 28.5
         ) %>%
  gather(xmin, xmax, key = "end", value = "x") %>%
  mutate(evodd = ifelse(neutnum %%2 ==1, "ev","odd"))
```



```{r upsettr bar plot}
intersect.bardat %>%
  ggplot(aes(x=x,y=n)) +
  geom_col() +
  labs(x = "", y = "") +
  theme_classic() +
  theme(axis.ticks.x = element_blank(),
        axis.text.x = element_blank()
        ) +
  ggsave("../../figures/upsetr_set-size.pdf")
```

```{r upsettr matrix plot}
corr.with.col %>%
  # mutate(neutlab = fct_relevel(neutlab, neutord)) %>%
  ggplot(aes(x = neutpair, y = neutnum, color = estimate)) +
  scale_x_discrete() +
  scale_y_discrete(breaks = as.character(c(1,2,3,4,5,6,7)), labels = neutord) + # if include LC, 8 breaks
  geom_ribbon(data = neutnumkey, inherit.aes = F,
              aes(ymin = ylow, ymax = yhigh, fill = evodd, alpha = 0.5, x = x, group = neutlab),
              show.legend = F) +
  scale_fill_manual(breaks = c("ev","odd"), values = c("grey70", "grey60")) +
  geom_point(size = 5) +
  geom_pointrange(aes(ymin = lownuet, ymax = highneut)) +
  # scale_color_distiller(guide = "legend", breaks = seq(-1,1,.2), 
  #                      limits = c(-1, 1), values = seq(0,1,.1),
  #                      type = "div", palette = "Spectral", direction = 1,
  #                      name = "Correlation") +
  scale_color_viridis(direction = -1, name = "Correlation", guide = "legend") +
  labs(x = "", y = "") +
  theme_bw() +
  theme(axis.ticks.x = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_text(),
        panel.grid = element_blank()
        ) 
ggsave("../../figures/upsetr_set-labels.pdf", width = 10)
```

## Related table: check genes in DESeq2 results

```{r}
load("prepared-data/des-res.rda")
intgenes <- c("G0S2", "IL8", "NAMPT", "PPP151A", "SOD2", "TREM1", "PLAUR", "PTGS2")

check.genes <- lapply(names(des.res), function(x) des.res[[x]] %>% 
                        mutate(Gene = as.character(Gene)) %>%
                        filter(Gene %in% intgenes) %>%
                        mutate(sig = padj < 0.05,
                               enriched.in = ifelse(log2FoldChange > 0, "treatment",
                                                    "control"),
                               neutgroup = x) %>%
                        select(neutgroup, Gene, sig, enriched.in))

bind_rows(check.genes) %>%
  write.csv("../../tables/genes-across-activations.csv", row.names = F)
```

# D: NMDS

```{r}
load("prepared-data/nmds-neut-counts.rda")
nmds.neuts.genes <- nmds.neuts.counts %>%
  filter(pointtype == "gene")
nmds.neuts.samples <- nmds.neuts.counts %>%
  filter(pointtype == "sample")
neuthulls <- nmds.neuts.samples %>%
  group_by(neutgroup) %>%
  slice(chull(MDS1,MDS2))

nmds.neuts.samples %>%
  ggplot(aes(x = MDS1, y = MDS2, color = neutgroup, fill= neutgroup,
             # label = pointlab, 
             alpha = pointtype)) +
  geom_point(data = nmds.neuts.counts, show.legend = F) +
  # stat_ellipse(geom = "polygon", alpha = .3) +
  geom_polygon(data = neuthulls, alpha = .3) +
  geom_point() +
  # geom_text_repel(show.legend = F) +
  scale_color_viridis(discrete = TRUE,option = "turbo", na.value = "grey66",
                      name = "Neutrophil",
                      breaks = c("airspace", "bldvat", "endotox", "exercise", "sepsis", "syno", "tb"),
                      labels = c("Airspace", "VAT", "Endotoxin", "Exercise", "Sepsis", 
                                 "Synovial", "Active TB")) +
  scale_fill_viridis(discrete = TRUE,option = "turbo", na.value = "grey66",
                      name = "Neutrophil",
                      breaks = c("airspace", "bldvat", "endotox", "exercise", "sepsis", "syno", "tb"),
                      labels = c("Airspace", "VAT", "Endotoxin", "Exercise", "Sepsis", 
                                 "Synovial", "Active TB")) +
  scale_alpha_manual(breaks = c("gene", "sample"), values = c(0.2, 1), guide = FALSE)+
  theme_bw() +
  theme(axis.text = element_blank(),
        axis.ticks = element_blank()) 
  ggsave("../../figures/nmds_neutrophil-state_counts.png",
         height = 3, width = 3)
```

# E: Signature score violin plot

```{r}
load("prepared-data/score-activation.rda")

treatment.scores %>%
  pivot_longer(-c("sample", "Neutrophil", "neutlabs"), names_to = "Pathway", values_to = "score") %>%
    ggplot(aes(x = score, y = neutlabs, fill = Neutrophil)) +
  facet_wrap(.~Pathway, nrow = 1, strip.position = "right") +
  geom_violin(show.legend = F) +
  scale_fill_viridis_d(option = "H") + 
  labs(x = "Signature Score", y = "") +
  theme_bw() +
  theme(text = element_text(size = 8)) 
  
   
ggsave("../../figures/violin_neut-pathway-comparison.png", width = 7, height = 3)
```


