---
title: "Top saline microbes"
author: "Rebecca Hoyd"
date: "11/30/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

# Load data

```{r}
tax <- read.table("../../data/mouse-data/second-experiment/ASV_tax_assignments.txt", stringsAsFactors = F, header = F, sep = "\t")

seqtab <- read.csv("../../data/mouse-data/second-experiment/ASV_Abundance_Table.csv")

abun <- read.csv("../../data/mouse-data/second-experiment/absolute.abundance.csv")
```

```{r}
zymo.seqtab <- read.csv("../../data/mouse-data/first-experiment/ASV_Abundance_Table.csv")
zymo.tax <- read.table("../../data/mouse-data/first-experiment/ASV_tax_assignments.txt", sep = "\t")

zymo.abun <-read.csv("../../data/mouse-data/first-experiment/absolute.abundance.csv")
```

# Formatting

```{r 2023 batch sample labels}
metadata <- seqtab %>%
  rename("sample" = "seqs") %>%
  select(sample) %>%
  # Pre-format the combined infor
  mutate(sample.form = gsub("Week\\.", "Week", 
                            gsub("VATO", "VAT.O", 
                                 gsub("\\.$","",
                                      gsub("\\.\\.",".", 
                                           gsub("long\\.","",
                                                gsub("Ly6G\\.","",
                                                     gsub("End\\.","",
                                                          gsub("Pellet\\.","",
                                                               gsub("T2..T6821","T6821(T2)",sample))))))))),
         sample.form = ifelse(grepl("Pellet", sample), paste0("Pellet.", sample.form), sample.form)
  ) %>%
  separate(sample.form,remove = F,
           into = c("tissue", "bmi.status", "space", "timepoint", "diet", "mouse", "patient", "patient.sex"), sep = "\\.") %>%
  # Fix pellet issues
  mutate(patient.sex = ifelse(tissue == "Pellet", patient, patient.sex),
         patient = ifelse(tissue == "Pellet",mouse, patient),
         mouse = ifelse(tissue == "Pellet", NA, mouse)) %>%
  # Fix obese, lean gavage
  mutate(gavage = grepl("slurry", sample),
         bmi.status = ifelse(gavage == T, tissue, bmi.status),
         tissue = ifelse(gavage == F, tissue, NA),
         patient.sex = ifelse(gavage == T, diet, patient.sex),
         patient = ifelse(gavage ==T, timepoint, patient),
         diet = ifelse(gavage == F, diet, NA),
         timepoint = ifelse(gavage == F, timepoint, NA)) %>%
  # Fix saline gavages
  mutate(gavage = gavage == T | tissue == "Saline",
         bmi.status = gsub("\\d", "Saline", bmi.status),
         tissue = ifelse(tissue == "Saline", NA, tissue)) %>%
  # Misc indicators
  mutate(Ly6G = grepl("Ly6G", sample),
         timepoint = gsub("Week1s", "Week1", timepoint),
         long.exp = grepl("long", sample)) %>%
# Fix patient IDs with infor from Dharti
  mutate(patient = ifelse(long.exp == T & bmi.status == "Obese", "T6821", patient),
         patient= ifelse(long.exp == F & bmi.status == "Obese" & tissue != "Pellet" & is.na(patient), "T6824", patient))

samps2023 <- metadata %>%
  mutate(diet = ifelse(grepl("HFD", diet), "HFD", diet)) %>%
  filter(tissue == "VAT" & bmi.status == "Saline" & timepoint == "Week1") %>%
  select(sample, diet)
```

```{r 2023 batch taxonomy}
tax.form <- tax %>%
  select(V1, V2) %>%
  separate(V2, into = c("kingdom", "phylum", "class", "order", "family", "genus", "species"), sep = ";") %>%
  mutate(phylum = ifelse(phylum == "p__NA", paste0("p__unclassified-", kingdom), phylum),
         class = ifelse(class == "c__NA", paste0("c__unclassified-", gsub("p__unclassified-", "", phylum)), class),
         order = ifelse(order == "o__NA", paste0("o__unclassified-", gsub("c__unclassified-", "", class)), order),
         family = ifelse(family == "f__NA", paste0("f__unclassified-", gsub("o__unclassified-", "", order)), family),
         genus = ifelse(genus == "g__NA", paste0("g__unclassified-", gsub("f__unclassified-", "", family)), genus),
         species = ifelse(species != "s__NA", 
                          paste0("s__", gsub("g__", "", genus),"-", gsub("s__", "", species)),
                          # species
                          paste0("s__unclassified-", gsub("g__unclassified-", "", genus))
         )
  )

abun.form <- abun %>%
  mutate(sample = customer_label) %>%
  select(sample, genome_copies_per_ul.)

seqtab.long <- seqtab %>%
  rename("sample" = "seqs") %>%
  inner_join(samps2023) %>%
  pivot_longer(-c("sample", "diet"), names_to = "V1", values_to = "counts") %>%
  mutate(ra = counts/sum(counts), .by = sample) %>%
  left_join(abun.form) %>%
  mutate(abs.abun = ra * genome_copies_per_ul.) %>%
  group_by(V1, diet) %>%
  summarize(medianAbsoluteAbundance = median(abs.abun)) %>%
  filter(medianAbsoluteAbundance > 0) %>%
  arrange(desc(medianAbsoluteAbundance)) %>%
  left_join(tax.form) %>%
  mutate(batch = "1")



```

```{r}
zymo.tax.form <- zymo.tax %>%
  select(V1, V2) %>%
  separate(V2, into = c("kingdom", "phylum", "class", "order", "family", "genus", "species"), sep = ";") %>%
  mutate(phylum = ifelse(phylum == "p__NA", paste0("p__unclassified-", kingdom), phylum),
         class = ifelse(class == "c__NA", paste0("c__unclassified-", gsub("p__unclassified-", "", phylum)), class),
         order = ifelse(order == "o__NA", paste0("o__unclassified-", gsub("c__unclassified-", "", class)), order),
         family = ifelse(family == "f__NA", paste0("f__unclassified-", gsub("o__unclassified-", "", order)), family),
         genus = ifelse(genus == "g__NA", paste0("g__unclassified-", gsub("f__unclassified-", "", family)), genus),
         species = ifelse(species != "s__NA", 
                          paste0("s__", gsub("g__", "", genus),"-", gsub("s__", "", species)),
                          # species
                          paste0("s__unclassified-", gsub("g__unclassified-", "", genus))
         )
  )

zymo.abun.form <- zymo.abun %>%
  mutate(sample = customer_label) %>%
  select(sample, genome_copies_per_ul.)

zymo.saline <- zymo.seqtab %>%
  filter(grepl("HFD.VAT", seqs)) %>%
  pivot_longer(-seqs, names_to = "V1", values_to = "counts") %>%
  mutate(sample = seqs) %>%
  mutate(ra = counts/sum(counts), .by = sample) %>%
  left_join(zymo.abun.form) %>%
  mutate(abs.abun = ra * genome_copies_per_ul.) %>%
  group_by(V1) %>%
  summarize(medianAbsoluteAbundance = median(abs.abun)) %>%
  filter(medianAbsoluteAbundance > 0) %>%
  arrange(desc(medianAbsoluteAbundance)) %>%
  left_join(zymo.tax.form) %>%
  mutate(batch = "2",
         diet = "HFD")
```
# Combine

```{r}
abundant.mics <- bind_rows(seqtab.long, zymo.saline) %>%
  pivot_wider(names_from = "diet", values_from = "medianAbsoluteAbundance", values_fill = 0)

write.csv(abundant.mics, "../../tables/saline-abundant-microbes.csv", row.names = F)
```
