---
title: "Supplement"
author: "Rebecca Hoyd"
date: "7/13/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(flextable)
library(dplyr)
library(ggplot2)
library(tidyr)
library(tibble)
library(stringr)
library(vegan)
library(forcats)
```


```{r}
accession.table <- read.csv("../../data/DESeq2/summarize-neutrgroup-sources.csv", stringsAsFactors = F)
```

# Table S2

```{r}
flextable(accession.table, cwidth = 2, cheight = 1.25)
```

# Table S4

```{r}
blood.files <- list.files("../../data/ncbi_processed/", pattern = "^Blood.*.txt")
blood.accession <- gsub(".*(GSE\\d+).*", "\\1", blood.files)
blood.accession <- as.data.frame(cbind(accession = c(blood.accession, "GSE19790"),
                                       tissue = "Blood"))


vat.files <- list.files("../../data/ncbi_processed/", pattern = "^VAT.*.txt")
vat.accession <- gsub(".*(GDS\\d+).*", "\\1", vat.files)
vat.accession <- as.data.frame(cbind(accession = c(vat.accession, "GSE71415"),
                                     tissue = "VAT"))
```

```{r}
bind_rows(blood.accession, vat.accession) %>%
  flextable(cwidth = 1)
```

# PCA zymo data

```{r}
zymo.seqtab <- read.csv("../../data/mouse-data/first-experiment/ASV_Abundance_Table.csv")

zymo.seqmeta <- zymo.seqtab %>%
  select(seqs) %>%
  separate(seqs, 
           into = c("gavage", "diet", "timepoint"),
           remove = F) %>%
  mutate(timepoint = str_sub(timepoint, 1, 3),
         exp.group = paste0(gavage, diet, timepoint),
         exp.group = ifelse(grepl("Pre", exp.group),
                            "Pre", 
                            ifelse(grepl("Pos", exp.group),
                                   "Pos",
                            exp.group)
         )
  ) %>%
  filter(timepoint %in% c("Pre", "Pos", "End") | is.na(diet)) 

pca.in <- zymo.seqtab %>%
  filter(seqs %in% zymo.seqmeta$seqs) %>%
  column_to_rownames(var = "seqs")

low.var <- unlist(lapply(pca.in, var))
low.var <- names(subset(low.var, low.var == 0))

pca.in <- pca.in %>%
  select(-low.var)

pca.res <- prcomp(pca.in, scale. = T)$x %>%
  as.data.frame() %>%
  rownames_to_column(var = "seqs") %>%
  left_join(zymo.seqmeta)

pca.res %>%
  mutate(exp.group = gsub("NANA", "", exp.group),
         exp.group = gsub("Pos", " Post", exp.group),
         exp.group = gsub("Pre", "Pre-antibiotic", exp.group)) %>%
  ggplot(aes(x = PC1, y = PC2, color = exp.group, fill = exp.group)) +
  stat_ellipse(geom = "polygon", alpha = .5, type = "norm") +
  geom_point() +
  scale_color_brewer(palette = "Set1",
                     aesthetics = c("color", "fill")) +
  theme_bw()

ggsave("../../figures/pca_zymo-stool.png")
```

```{r}
distmat <- pca.in %>%
  vegdist(method = "gower", binary=FALSE, diag=FALSE, upper=FALSE,
        na.rm = FALSE) %>%
  as.matrix() %>%
  as.data.frame() %>%
  rownames_to_column(var = "sample") %>%
  filter(!sample %in% c("Obesegavage", "Leangavage")) %>%
  select(sample, Leangavage, Obesegavage) %>%
  pivot_longer(-sample, names_to = "gavageDist", values_to = "distance") %>%
  separate(sample, into = c("gavage", "diet", "timepoint"), remove = F) %>%
  mutate(timepoint = gsub("\\d$", "", timepoint),
         diet.group = ifelse(timepoint == "End", paste(gavage, diet), NA)) %>%
  filter(gavage == gavageDist)

distmat %>%
  mutate(timepoint = fct_relevel(timepoint, "Pre", "Post"),
         diet.group = ifelse(is.na(diet.group),
                             "Before diet",
                             gsub("gavage", " gavage,", diet.group))) %>%
  ggplot(aes(x = timepoint, y = 1-distance 
             # fill = diet.group
             )) +
  geom_boxplot(fill = "grey") +
  geom_point() +
  labs(x = "Time point", y = "Similarity to Gavage") +
  scale_x_discrete(breaks = c("Pre", "Post", "End"),
          labels = c("Pre-ABx", "Post-ABx", 
                     "End")) +
  # scale_fill_brewer(palette = "Dark2", name = "Diet group",
  #                   na.value = "grey") +
  theme_bw()
ggsave("../../figures/boxplot_zymo_distance-from-gavage.png", width = 4, height = 3)
```

# Boxplots absolute abundance

```{r}
zymo.abun.abs <- read.csv("../../data/mouse-data/first-experiment/absolute.abundance.csv")

stool.samps <- zymo.abun.abs %>%
  separate(customer_label, into = c("gavage", "diet", "timepoint")) %>%
  mutate(timepoint = str_sub(timepoint, 1, 3)) %>%
  filter(timepoint %in% c("Pre", "Pos", "End")) %>%
  mutate(timepoint = fct_relevel(timepoint, "Pre", "Pos", "End"))

stool.samps %>%
  ggplot(aes(x = timepoint, y = log(gene_copies_per_ul))) +
  geom_boxplot() +
  geom_point() +
  scale_x_discrete(breaks = c("Pre", "Pos", "End"),
          labels = c("Pre-antibiotic", "Post-antibiotic", 
                     "Study end")) +
  labs(x = "Time point", y = "log(Gene copies per ul sample)") +
  theme_bw()
ggsave("../../figures/boxplot_zymo-absolute-abundance.png")
```