---
title: "Check for contaminants"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(tibble)
library(decontam)
library(tidyr)
```

# Load data

```{r}
seqtab <- readRDS("../data/seqtabNoCf_update.RDS")
tax <- readRDS("../data/taxf_update.RDS")

meta <- read.csv("../data/ATBACSAMPLESrna-dna.csv", stringsAsFactors = F)
```

# Manipulate to DNA interface layer samples

```{r}
meta.f <- meta %>%
  filter((grepl("-I", Sample.ID) & Sample.Type == "DNA") | Sample.ID == "AB014-NEG") %>%
  group_by(Sample.ID) %>%
  summarize(Nucleic.con = max(Nucleic.Acid.Conc.)) %>%
  mutate(Sample.ID = ifelse(grepl("NEG", Sample.ID), "ABNEG", Sample.ID),
         Nucleic.con = Nucleic.con + 0.7) %>% # Minimum concentration is -.6, decontam only accepts positive []
  arrange(Sample.ID)

seqtab.f <- seqtab %>%
  as.data.frame() %>%
  rownames_to_column(var = "sample") %>%
  filter(grepl("-CI", sample)|sample == "ABNEG-C")

meta.fr <- meta.f[-13,]
seqtab.fr <- seqtab.f[-15,]

negvec <- c(rep(FALSE, 16), TRUE)
```

# run decontam

We don't find any contaminants using this process.
```{r}
checkvals <- isContaminant(as.matrix(seqtab.fr[,-1]), conc = meta.fr$Nucleic.con, neg = negvec)

any(checkvals$contaminant == TRUE)
```

# Which organisms appear in the negative control?

```{r}
tax.form <- tax %>%
  as.data.frame() %>%
  rownames_to_column(var = "Sequence")

taxcounts <- seqtab.f %>%
  gather(-sample, key = "Sequence", value = "counts") %>%
  left_join(tax.form) 

present.in.neg <- taxcounts %>%
  filter(sample == "ABNEG-C") %>%
  mutate(negpres = ifelse(counts > 0, TRUE, FALSE)) %>%
  select(Sequence, negpres)
```

```{r}
taxcounts.neg <- taxcounts %>%
  left_join(present.in.neg)

# Overall percentage of counts from negative organisms?
taxcounts.neg %>%
  group_by(negpres) %>%
  summarise(counts = sum(counts)) %>%
  mutate(percent.counts = counts/sum(counts))

# Which taxa are in the negative control?

taxcounts.negtax <- taxcounts.neg %>%
  filter(negpres == TRUE) %>%
  group_by(Sequence) %>%
  summarize(total.counts = sum(counts)) %>%
  left_join(tax.form)

taxcounts.negtax
```

```{r}
# How representative of proteobacteria is this group?

taxcounts.neg %>%
  filter(Phylum == "Proteobacteria") %>%
  mutate(Genus = ifelse(Genus == "Stakelama", "Stakelama", "Other")) %>%
  group_by(Genus) %>%
  summarise(counts = sum(counts))
```

## What's the percentage of sequences in the control?

```{r}
mean(present.in.neg$negpres)
```