---
title: "AT bacteria"
author: "Rebecca Hoyd"
date: "January 16, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(ggfortify)
library(tidyr)
library(dplyr)
library(tibble)
library(forcats)
library(RColorBrewer)
```

# Load data

```{r}
seqtab <- readRDS("../data/seqtabNoCf_update.RDS")
tax <- readRDS("../data/taxf_update.RDS")

bmi.stat <- read.csv("../data/samples_obesity-status.csv", stringsAsFactors = F) %>%
  select(-sample.name) %>%
  mutate(label = paste0(sequence.id, "_int")) %>%
  filter(!is.na(BMI))
```

# Manipulate 

```{r}
tax <- tax %>%
  as.data.frame() %>%
  rownames_to_column(var = "Sequence")

taxcounts <- seqtab %>%
  as.data.frame() %>%
  rownames_to_column(var = "sample") %>%
  gather(-sample, key = "Sequence", value = "count") %>%
  left_join(tax)
```

```{r}
taxcounts.phyl <- taxcounts %>%
  as.data.frame() %>%
  mutate(Phylum = as.character(Phylum),
         Phylum = ifelse(is.na(Phylum), "Unclassified", Phylum)) %>%
  group_by(sample, Phylum) %>%
  summarise(count = sum(count)) 

taxcounts.fam <- taxcounts %>%
  group_by(sample, Family) %>%
  summarise(count = sum(count)) %>%
  spread(key = "Family", value = "count")
```

# Stacked bar

```{r}
taxcounts.phyl %>%
  mutate(seqtype = ifelse(grepl("-C", sample), "RNA", "DNA")) %>%
  ggplot(aes(x = sample, y = count, fill = Phylum)) +
  geom_col(position = "fill") +
  facet_wrap(vars(seqtype), scales = "free_x") +
  labs(x = "", y = "") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust=1, size = 8, vjust = .5)) +
  ggsave("../figures/stacked-bar_phyla.png", width = 10)
```


# PCA
```{r}
pr.res <- prcomp(taxcounts.fam[,-1], scale. = T)

meta <- taxcounts.fam %>%
  as.data.frame() %>%
  select(sample) %>%
  mutate(sampid = gsub("(.*)-.*", "\\1", sample),
         neg = ifelse(grepl("NEG", sampid), "NEG", "sample"))

rownames(meta) <- meta$sample
```

```{r}
autoplot(pr.res, data = meta, colour = 'neg') +
  theme_bw() +
  ggsave("../figures/quick-pca.png")
```

# Histogram of counts

```{r}
famsum <- taxcounts.fam %>%
  gather(-sample, key = 'family', value = 'count') %>%
  group_by(sample) %>%
  summarize(totalmic = sum(count))

famsum %>%
  ggplot(aes(x = totalmic)) +
  geom_histogram() +
  theme_bw() +
  ggsave("../figures/histogram_family-counts.png")

famsum %>%
  filter(totalmic < 2000) %>%
  ggplot(aes(x = totalmic)) +
  geom_histogram() +
  theme_bw() +
  ggsave("../figures/histogram_family-counts_remlarge.png")
```

# Stacked bar, DNA with ordering

```{r}
getsampord <- bmi.stat %>%
  arrange(BMI) %>%
  mutate(sample = paste0(sequence.id, "-I"))

getsampord %>%
  mutate(count = 1) %>%
  ggplot(aes(x=0, y = count, fill = BMI)) +
  geom_col(position = "fill") +
  scale_fill_manual(breaks = c("Lean", "Obese"), values = c("grey", "black")) +
  coord_flip() +
  theme_void() +
  ggsave("../figures/BMI-labels-for-ordered-stack.png", width = 10, height = 1)
  
```

```{r}
getPalette <- colorRampPalette(brewer.pal(11, "Spectral"))
phyls <- unique(as.character(taxcounts.phyl$Phylum))
use.palette <- getPalette(12)
use.palette[11] <- "grey"

taxcounts.phyl %>%
  mutate(seqtype = ifelse(grepl("-C", sample), "RNA", "DNA")) %>%
  filter(seqtype == "DNA" & !grepl("ABNEG", sample) & grepl("-I", sample)) %>%
  left_join(getsampord) %>%
  ggplot(aes(x = fct_relevel(sample, rev(getsampord$sample)), y = count, fill = Phylum)) +
  geom_col(position = "fill") +
  scale_fill_manual(breaks = phyls, values = use.palette) + 
  labs(x = "", y = "") +
  theme_bw() +
  theme(axis.text.x = element_blank()) +
  ggsave("../figures/stacked-bar_phyla_DNA-ordered.png", width = 10)
```