---
title: "16S absolute abundance"
format: html
editor: visual
---

```{r}

library(tidyverse)

```

 

```{r load data}

x <- read_csv("../data/zymo_abs-abundance.csv") %>%
  drop_na(sample_id)

head(x)
```

```{r}

tissue <- 
  x %>%
  mutate(source = if_else(grepl("Pre|Post|End|^Leangavage$|^Obesegavage$", customer_label),
                          true = "stool",
                          false = "tissue"),
         tissue_type = if_else(grepl("VAT", customer_label),
                               true = "VAT",
                               false = if_else(grepl("Liver", customer_label),
                                               true = "Liver",
                                               false = if_else(grepl("Brain", customer_label),
                                                               true = "Brain",
                                                               false = "stool"))),
         Gavage = if_else(grepl("Lean", customer_label),
                             true = "Lean",
                             false = if_else(grepl("Obese", customer_label),
                                             true = "Obese",
                                             false = "Saline")),
         Diet = if_else(grepl("HFD", customer_label),
                        true = "HFD",
                        false = if_else(grepl("Chow", customer_label),
                                        true = "Chow",
                                        false = "Other")))


tissue %>%
  group_by(source, tissue_type, Gavage, Diet) %>%
  summarize(n = n())
```

```{r}
tissue %>%
  filter(source == "tissue") %>%
  mutate(dietdummy = ifelse(tissue_type == "VAT", Diet, "HFD")) %>%
  ggplot(aes(x = Gavage, y = log(`genome_copies_per_ul*`))) +
  facet_wrap(vars(tissue_type), nrow = 1, strip.position = "bottom") +
  geom_boxplot(aes(fill = Gavage, color = dietdummy), 
               outlier.shape = NA
               ) +
  geom_point(aes(shape = Diet, 
                 fill = Gavage,
                 group = dietdummy), 
             size = 3,
             color = "grey30",
             position = position_jitterdodge(jitter.width = .1)
             ) +
  
  theme_bw(base_size = 10) +
  scale_fill_manual(breaks = c("Lean", "Obese", "Saline"),
                    values = c("#A76686","#94BBC6","#FEFE7D"),
                    aesthetics = c( "fill")) +
  scale_shape_manual(breaks = c("Chow", 
                                "HFD"),
                     values = c(21,
                                24)
                     ) +
  scale_color_manual(values = c("grey25", "grey30")) +
  labs(x = "",
       y = "Log(Microbe Genome Copies per ul)") +
  guides(shape = guide_legend(override.aes = list(fill = "black")),
         fill = guide_legend(override.aes = list(shape = NA)),
         color = F) +
  theme_bw() +
  theme(axis.ticks.x = element_blank(),
        axis.text.x = element_blank())

ggsave("../figures/zymo_abs-abundance_tissues.png",
     height = 4, width = 6)
```
