---
title: "DESeq2 visualization"
author: "Daniel Spakowicz"
date: "6/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggrepel)
```

```{r}
d <- read.csv("../data/DESeq2_all-levs_DNA.csv", stringsAsFactors = F)
```

```{r}
d %>%
  filter(pvalue < 0.1) %>%
  mutate(dir = ifelse(log2FoldChange > 0, "pos", "neg")) %>%
  filter(!grepl("Eukaryota|Sphingomonadaceae", Taxa)) %>%
  ggplot(aes(x = log2FoldChange, y = reorder(Taxa, log2FoldChange))) +
  geom_bar(stat = "identity", aes(fill = dir), show.legend = FALSE) +
  labs(x = "Log Fold Change",
       y = "") +
  theme_bw() +
  ggsave("../figures/DESeq2_all-levs_DNA_top-sig_bar.png", 
         height = 2, width = 4)
         
```

# Volcano plot

```{r}
head(d)
```

```{r}
d %>%
  mutate(colgroup = ifelse(pvalue < 0.1, Taxa.Level, NA)) %>%
  ggplot(aes(x = log2FoldChange, y = -log(pvalue), color = colgroup)) +
  geom_point() +
  geom_text_repel(aes(label = ifelse(!is.na(colgroup), Taxa, NA))) +
  geom_hline(yintercept = -log(.1), linetype = "dashed") +
  geom_vline(xintercept = -2, linetype = "dashed") +
  geom_vline(xintercept = 2, linetype = "dashed") +
  scale_color_brewer(palette = "Dark2", na.value = "grey50", name = "Taxonomy Level") +
  theme_bw() +
  ggsave("../figures/volcano_deseq2-DNA-results.pdf")
```

