---
title: "modelling Obese v Lean Zymo 2023/9"
author: "Rebecca Hoyd"
date: "9/27/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(glmm)
library(broom)
library(rlist)
library(ggrepel)
library(RColorBrewer)
```

# Load data

```{r}
tax <- read.table("/fs/ess/PAS1695/projects/atbac/data/zymo/onedrive_2023-09-27/zr13065.16S_230916.zymo/00...AllSamples.Bac16Sv34/DADA2_ASV_Distribution/ASV_tax_assignments.txt", stringsAsFactors = F, header = F, sep = "\t")
seqtab <- read.csv("/fs/ess/PAS1695/projects/atbac/data/zymo/onedrive_2023-09-27/zr13065.16S_230916.zymo/00...AllSamples.Bac16Sv34/DADA2_ASV_Distribution/ASV_Abundance_Table.csv")
```

# Functions

```{r}
exoRAtowide <- function(data, taxlev){
  tmp <- data
  tmp$Taxa <- tmp[[taxlev]]
  tmp.wide<- tmp %>%
    dplyr::filter(!is.na(Taxa)) %>%
    group_by(sample, Taxa) %>%
    summarise(ra = sum(relabun, na.rm = T)) %>%
    spread(key = "Taxa", value = "ra")
  
  tmp.wide[is.na(tmp.wide)] <- 0
  return(tmp.wide)
}

exoToDF <- function(taxalevels = c("kingdom", "phylum", "class", 
                                    "order", "family", "genus", "species"), 
                     data){
  w.ls <- lapply(taxalevels, function(x) exoRAtowide(data, x))
  w.df <- reduce(w.ls, function(x,y) left_join(x,y)) 
  return(w.df)
}
```

```{r logistic regression functions}
capture.models.univ.former <- function(outcome, lfun, mics, modin){
  mods.list <- lapply(mics, function(x)  try({glm(as.formula(paste0(outcome, " ~ `", x,"`")), family = lfun, data = modin) %>% tidy()}))
  mods.list.clean <- list.clean(mods.list, function(x) is.null(x))
  mods.df <- bind_rows(mods.list.clean) %>%
    filter(term != "(Intercept)")
  return(mods.df)
}


univ.model.format <- function(set1) {
  modelin <- set1 %>%
    left_join(relabun.w)
  
  set1.res <- capture.models.univ.former("binom.ind", "binomial", microbes, modelin)
  return(set1.res)
}
```

```{r calculate l2fc}
calculateL2FC <- function(set1){
  fcs <- set1 %>%
    select(sample, binom.ind) %>%
    left_join(relabun.w) %>%
    pivot_longer(-c("sample", "binom.ind"), names_to = "term", values_to = "relabun") %>%
    group_by(binom.ind, term) %>%
    summarise(gmean = mean(relabun)) %>%
    mutate(binom.ind = paste0("b", binom.ind)) %>%
    pivot_wider(names_from = binom.ind, values_from = gmean) %>%
    mutate(log2fc = log(b1/b0, base = 2)) %>%
    select(term, log2fc)
  
  return(fcs)
}
```

```{r}
quickVolPlot <- function(pvals, fcs){
  volin <- pvals %>%
    drop_na(p.value) %>%
    left_join(fcs) %>%
    mutate(colind = ifelse(p.value < 0.05, str_sub(term, 1,1),NA),
           labtext = ifelse(p.value < 0.05, term,NA))
  
  taxacols <- brewer.pal(7,"Set1")
  names(taxacols) <- c("k", "p", "c", "o", "f", "g", "s")
  
  volin %>%
    ggplot(aes(x = log2fc, y = -log(p.value), label = labtext)) +
    geom_point(aes(color = colind)) +
    geom_text_repel() +
    geom_hline(yintercept = -log(0.05), lty = 2) +
    geom_vline(xintercept = 0, lty = 2) +
    scale_color_manual(values = taxacols, name = "Taxonomic\nlevel") +
    theme_bw()
}

rangeFormatting <- function(pvals, fcs, patlab){
  volin <- pvals %>%
    drop_na(p.value) %>%
    mutate(term = str_remove_all(term, "`")) %>%
    left_join(fcs) %>%
    mutate(colind = ifelse(p.value < 0.05, str_sub(term, 1,1),NA),
           labtext = ifelse(p.value < 0.05, term,NA),
           patient = patlab)
  
  return(volin)
}
```

# Formatting

```{r wide relative abundances}
tax.form <- tax %>%
  select(V1, V2) %>%
  separate(V2, into = c("kingdom", "phylum", "class", "order", "family", "genus", "species"), sep = ";") %>%
  mutate(phylum = ifelse(phylum == "p__NA", paste0("p__unclassified-", kingdom), phylum),
         class = ifelse(class == "c__NA", paste0("c__unclassified-", gsub("p__unclassified-", "", phylum)), class),
         order = ifelse(order == "o__NA", paste0("o__unclassified-", gsub("c__unclassified-", "", class)), order),
         family = ifelse(family == "f__NA", paste0("f__unclassified-", gsub("o__unclassified-", "", order)), family),
         genus = ifelse(genus == "g__NA", paste0("g__unclassified-", gsub("f__unclassified-", "", family)), genus),
         species = ifelse(species != "s__NA", 
                          paste0("s__", gsub("g__", "", genus),"-", gsub("s__", "", species)),
                          # species
                          paste0("s__unclassified-", gsub("g__unclassified-", "", genus))
         )
  )


seqtab.long <- seqtab %>%
  pivot_longer(-seqs, names_to = "V1", values_to = "counts") %>%
  mutate(samptot = sum(counts), .by = seqs) %>%
  mutate(relabun = counts/samptot) %>%
  left_join(tax.form) %>%
  drop_na() %>%
  select(-samptot, -V1, -counts) %>%
  rename("sample" = "seqs")

relabun.w <- exoToDF(data = seqtab.long)

microbes <- colnames(relabun.w)[-1]
```

```{r sample info}
metadata <- relabun.w %>%
  select(sample) %>%
  # Pre-format the combined infor
  mutate(sample.form = gsub("Week\\.", "Week", 
                            gsub("VATO", "VAT.O", 
                                 gsub("\\.$","",
                                      gsub("\\.\\.",".", 
                                           gsub("long\\.","",
                                                gsub("Ly6G\\.","",
                                                     gsub("End\\.","",
                                                          gsub("Pellet\\.","",
                                                               gsub("T2..T6821","T6821(T2)",sample))))))))),
         sample.form = ifelse(grepl("Pellet", sample), paste0("Pellet.", sample.form), sample.form)
  ) %>%
  separate(sample.form,remove = F,
           into = c("tissue", "bmi.status", "space", "timepoint", "diet", "mouse", "patient", "patient.sex"), sep = "\\.") %>%
  # Fix pellet issues
  mutate(patient.sex = ifelse(tissue == "Pellet", patient, patient.sex),
         patient = ifelse(tissue == "Pellet",mouse, patient),
         mouse = ifelse(tissue == "Pellet", NA, mouse)) %>%
  # Fix obese, lean gavage
  mutate(gavage = grepl("slurry", sample),
         bmi.status = ifelse(gavage == T, tissue, bmi.status),
         tissue = ifelse(gavage == F, tissue, NA),
         patient.sex = ifelse(gavage == T, diet, patient.sex),
         patient = ifelse(gavage ==T, timepoint, patient),
         diet = ifelse(gavage == F, diet, NA),
         timepoint = ifelse(gavage == F, timepoint, NA)) %>%
  # Fix saline gavages
  mutate(gavage = gavage == T | tissue == "Saline",
         bmi.status = gsub("\\d", "Saline", bmi.status),
         tissue = ifelse(tissue == "Saline", NA, tissue)) %>%
  # Misc indicators
  mutate(Ly6G = grepl("Ly6G", sample),
         timepoint = gsub("Week1s", "Week1", timepoint),
         long.exp = grepl("long", sample)) %>%
# Fix patient IDs with infor from Dharti
  mutate(patient = ifelse(long.exp == T & bmi.status == "Obese", "T6821", patient),
         patient= ifelse(long.exp == F & bmi.status == "Obese" & tissue != "Pellet" & is.na(patient), "T6824", patient))
```

# Analyses

## Model short experiments

```{r, message=FALSE,warning=FALSE}
sampset.OvL.short.p1 <- metadata %>%
  filter(long.exp == F & gavage == F &
           tissue == "VAT" &
           (bmi.status == "Lean" | patient == "T6820")) %>%
  mutate(binom.ind = ifelse(bmi.status == "Lean", 0,1))

mres.OvL.short.p1 <- univ.model.format(sampset.OvL.short.p1)
fc.OvL.short.p1 <- calculateL2FC(sampset.OvL.short.p1)

quickVolPlot(mres.OvL.short.p1, fc.OvL.short.p1)
```

```{r, message=FALSE,warning=FALSE}
sampset.OvL.short.p2 <- metadata %>%
  filter(long.exp == F & gavage == F &
           tissue == "VAT" &
           (bmi.status == "Lean" | patient == "T6821")|
           (long.exp == T & gavage == F & timepoint == "Week1" & bmi.status == "Obese" & Ly6G == F & diet == "HFD")) %>%
  mutate(binom.ind = ifelse(bmi.status == "Lean", 0,1))

mres.OvL.short.p2 <- univ.model.format(sampset.OvL.short.p2)
fc.OvL.short.p2 <- calculateL2FC(sampset.OvL.short.p2)

quickVolPlot(mres.OvL.short.p2, fc.OvL.short.p2)
```

```{r, message=FALSE,warning=FALSE}
sampset.OvL.short.p3 <- metadata %>%
  filter(long.exp == F & gavage == F &
           tissue == "VAT" &
           (bmi.status == "Lean" | patient == "T6824")) %>%
  mutate(binom.ind = ifelse(bmi.status == "Lean", 0,1))

mres.OvL.short.p3 <- univ.model.format(sampset.OvL.short.p3)
fc.OvL.short.p3 <- calculateL2FC(sampset.OvL.short.p3)

quickVolPlot(mres.OvL.short.p3, fc.OvL.short.p3)
```


```{r, message=FALSE,warning=FALSE}
sampset.OvL.short <- metadata %>%
  filter((long.exp == F & gavage == F &
           tissue == "VAT" &
           bmi.status != "Saline") |
           (long.exp == T & gavage == F & timepoint == "Week1" & bmi.status == "Obese" & Ly6G == F & diet == "HFD")) %>%
  mutate(binom.ind = ifelse(bmi.status == "Lean", 0,1))

mres.OvL.short <- univ.model.format(sampset.OvL.short)
fc.OvL.short <- calculateL2FC(sampset.OvL.short)

quickVolPlot(mres.OvL.short, fc.OvL.short)
```

## Long experiments - saline

```{r, message=FALSE,warning=FALSE}
sampset.OvS.w1 <- metadata %>%
  filter(long.exp == T & gavage == F &
           tissue == "VAT" & Ly6G == F &
           timepoint == "Week1" & diet == "HFD") %>%
  mutate(binom.ind = ifelse(bmi.status == "Saline", 0,1))

mres.OvS.w1 <- univ.model.format(sampset.OvS.w1)
fc.OvS.w1 <- calculateL2FC(sampset.OvS.w1)

quickVolPlot(mres.OvS.w1, fc.OvS.w1)
```

```{r, message=FALSE,warning=FALSE}
sampset.OvS.w3 <- metadata %>%
  filter(long.exp == T & gavage == F &
           tissue == "VAT" & Ly6G == F &
           timepoint == "Week3" & diet == "HFD") %>%
  mutate(binom.ind = ifelse(bmi.status == "Saline", 0,1))

mres.OvS.w3 <- univ.model.format(sampset.OvS.w3)
fc.OvS.w3 <- calculateL2FC(sampset.OvS.w3)

quickVolPlot(mres.OvS.w3, fc.OvS.w3)
```

```{r, message=FALSE,warning=FALSE}
sampset.OvS.w5 <- metadata %>%
  filter(long.exp == T & gavage == F &
           tissue == "VAT" & Ly6G == F &
           timepoint == "Week5" & diet == "HFD") %>%
  mutate(binom.ind = ifelse(bmi.status == "Saline", 0,1))

mres.OvS.w5 <- univ.model.format(sampset.OvS.w5)
fc.OvS.w5 <- calculateL2FC(sampset.OvS.w5)

quickVolPlot(mres.OvS.w5, fc.OvS.w5)
```

## Long experiments - ly6g

```{r, message=FALSE,warning=FALSE}
sampset.OvLy.w1 <- metadata %>%
  filter(long.exp == T & gavage == F &
           tissue == "VAT" & bmi.status == "Obese" &
           timepoint == "Week1" & diet == "HFD") %>%
  mutate(binom.ind = ifelse(Ly6G == F, 0,1))

mres.OvLy.w1 <- univ.model.format(sampset.OvLy.w1)
fc.OvLy.w1 <- calculateL2FC(sampset.OvLy.w1)

quickVolPlot(mres.OvLy.w1, fc.OvLy.w1)
```

```{r, message=FALSE,warning=FALSE}
sampset.OvLy.w3 <- metadata %>%
  filter(long.exp == T & gavage == F &
           tissue == "VAT" & bmi.status == "Obese" &
           timepoint == "Week3" & diet == "HFD") %>%
  mutate(binom.ind = ifelse(Ly6G == F, 0,1))

mres.OvLy.w3 <- univ.model.format(sampset.OvLy.w3)
fc.OvLy.w3 <- calculateL2FC(sampset.OvLy.w3)

quickVolPlot(mres.OvLy.w3, fc.OvLy.w3)
```

```{r, message=FALSE,warning=FALSE}
sampset.OvLy.w5 <- metadata %>%
  filter(long.exp == T & gavage == F &
           tissue == "VAT" & bmi.status == "Obese" &
           timepoint == "Week5" & diet == "HFD") %>%
  mutate(binom.ind = ifelse(Ly6G == F, 0,1))

mres.OvLy.w5 <- univ.model.format(sampset.OvLy.w5)
fc.OvLy.w5 <- calculateL2FC(sampset.OvLy.w5)

quickVolPlot(mres.OvLy.w5, fc.OvLy.w5)
```

## Pellets

```{r}
sampset.pellets <- metadata %>%
  filter(tissue == "Pellet" & diet == "HFD" & timepoint == "Week1" & bmi.status != "Saline" & Ly6G == F) %>%
  mutate(binom.ind = ifelse(bmi.status == "Lean", 0,1))

mres.pellets <- univ.model.format(sampset.pellets)
fc.pellets <- calculateL2FC(sampset.pellets)

quickVolPlot(mres.pellets, fc.pellets)
```

# Summaries

## Short experiments

```{r}
sig.OvL.p1 <- mres.OvL.short.p1 %>%
  mutate(patient = "T6820") %>%
  filter(p.value < 0.05)

sig.OvL.p2 <- mres.OvL.short.p2 %>%
  mutate(patient = "T6821") %>%
  filter(p.value < 0.05)

sig.OvL.p3 <- mres.OvL.short.p3 %>%
  mutate(patient = "T6824") %>%
  filter(p.value < 0.05)


sig.OvL.short <- bind_rows(sig.OvL.p1,sig.OvL.p2,sig.OvL.p3)
sig.OvL.short
write.csv(sig.OvL.short, "../data/modelling_significant_OvL-short.csv", row.names = F)
```

## Volcanic Range plot

```{r}
modres.forrange <- list("T6820" = list(mres.OvL.short.p1, fc.OvL.short.p1),
                        "T6821" = list(mres.OvL.short.p2, fc.OvL.short.p2),
                        "T6824" = list(mres.OvL.short.p3, fc.OvL.short.p3))

rangedat <-lapply(names(modres.forrange), function(x) rangeFormatting(modres.forrange[[x]][[1]],
                                                                      modres.forrange[[x]][[2]],
                                                                      x)) %>%
  bind_rows()
```

```{r}
proteobacteria <- tax.form %>%
  filter(phylum == "p__Proteobacteria") %>%
  select(-V1,) %>%
  pivot_longer(-kingdom, names_to = "level", values_to = "values") %>%
  select(values) %>%
  distinct()

rangedat.form <- rangedat %>%
  mutate(t6820.ind = p.value == min(p.value), .by = patient) %>%
  mutate(direction = ifelse(log2fc < 0, "Lean", "Obese"),
         patnum = as.numeric(as.factor(patient)),
         protval = ifelse(term %in% proteobacteria$values, "Proteobacteria", "Not Proteobacteria"),
         nudgeval = ifelse(protval == "Proteobacteria", .15,.1),
         patval = ifelse(direction == "Lean", patnum - nudgeval, patnum + nudgeval),
         sizeval = case_when(abs(log2fc) < 1 ~ "a",
                             abs(log2fc) < 2 ~ "b",
                             abs(log2fc) >=2  ~ "c"),
         pointlab = ifelse(term == "g__Noviherbaspirillum" & patient == "T6820",
                           "Noviherbaspirillum",
                           gsub("-", " ", str_remove_all(str_remove(labtext, "\\w__"), "`")))
  )

patkey <- rangedat.form %>%
  select(patnum, patient) %>%
  distinct()

save(rangedat.form, patkey, file = "../data/plotdat_mouse-exp_vulcanrange.rda")
rangedat.form %>%
  drop_na(direction) %>%
  ggplot(aes(x = patval, y = -log(p.value), shape = protval)) +
  geom_point(aes(size = sizeval, color =direction)) +
  geom_text_repel(aes(label = pointlab), size = 3) +
  scale_color_brewer(palette = "Set1", name = "", labels = c("Depleted in Obese", "Enriched in Obese")) +
  scale_x_continuous(breaks = patkey$patnum, labels = patkey$patient) +
  scale_size_manual(breaks = c("a", "b", "c"), 
                    values = c(1,2,3), 
                    labels = c("<1", "<2", ">=2"),
                    name = "log2FoldChange") +
  scale_shape(name = "") +
  labs(x = "Patient") +
  theme_bw() +
  theme(text = element_text(size = 9))
ggsave("../figures/vulcanrange_mouse-short.png")

# rangedat.form %>%
#   drop_na(direction) %>%
#   ggplot(aes(x = log2fc, y = -log(p.value)
#              # size = sizeval, color =direction
#              )
#          ) +
#   facet_wrap(vars(patient), ncol = 1) +
#   geom_point() +
#   theme_bw()
# ggsave("../figures/volcano_faceted_mouse-short.png")
```

```{r}
library(plotly)
plot_ly(y=rangedat.form$log2fc, z=-log(rangedat.form$p.value), x=rangedat.form$patient, type="scatter3d")
rangedat.form %>%
  ggplot(aes(y = as.factor(patient), z = -log(p.value), x = log2fc)) +
  geom_point_z() +
  # scale_color_brewer(palette = "Set1", name = "BMI status") +
  # scale_x_continuous(breaks = patkey$patnum, labels = patkey$patient) +
  # scale_size_manual(breaks = c("a", "b", "c"), 
  #                   values = c(1,2,3), 
  #                   labels = c("<1", "<2", ">=2"),
  #                   name = "log2FoldChange") +
  # labs(x = "Patient") +
  theme_bw()
```

# Check presence of significant microbes in stool, gavage

```{r}
sig.OvL.short <- read.csv("../data/modelling_significant_OvL-short.csv")

likelysamps <- metadata %>%
  filter(bmi.status == "Obese" & (tissue == "Pellet" | gavage == T))
joinmics <- sig.OvL.short %>%
  select(term,patient) %>%
  inner_join(likelysamps) %>% 
  select(sample, term, patient) %>%
  mutate(term = str_remove_all(term, "`"))


relabun.long.sig <- relabun.w %>%
  pivot_longer(-sample, names_to = "term", values_to = "relabun") %>%
  inner_join(joinmics)
```

```{r}
relabun.long.sig %>%
  mutate(prev = relabun > 0) %>%
  ggplot(aes(x = sample, y = term, fill = prev)) +
  facet_wrap(vars(patient), scales = "free") +
  geom_tile() +
  theme_bw()
```

```{r}
relabun.w %>%
  select(sample, str_remove_all(sig.OvL.short$term, "`"),  "g__Pseudomonas" , "g__Sphingomonas") %>%
  pivot_longer(-sample, names_to ="microbe", values_to = "relabun") %>%
  left_join(metadata) %>%
  mutate(tissue = replace_na(tissue, "Gavage.slurry")) %>%
  mutate(prev = relabun > 0) %>%
  group_by(microbe, tissue) %>%
  summarize(prev = mean(prev)) %>%
  pivot_wider(names_from = "tissue", values_from = "prev")
```
