---
title: "gtex grant fig"
author: "Caroline Wheeler"
date: "9/28/2023"
output: html_document
---

##combine deconv data
```{r combine deconvolved data}
library(readr)
library(tibble)
library(dplyr)
## combine results

files_CUS <- list.files(path = "../../manuscript/data/CIBERSORT/CIBERSORTx-deconvolved/GTEx", pattern = "*_CUS.csv", full.names = T)
ciber_CUS <- sapply(files_CUS, read_csv, simplify=FALSE) %>% bind_rows(.id = "id")
ciber_CUS$Mixture <- as.factor(ciber_CUS$Mixture)
ciber_CUS$Mixture <- gsub("(GTEX)\\.(.*)\\.(\\d+)\\.(.*)\\.(SM)\\.(.*)", "\\1\\-\\2\\-\\3\\-\\4\\-\\5\\-\\6",ciber_CUS$Mixture)
ciber_CUS$Mixture <- gsub("(GTEX)\\.(.*)\\.(\\d+)\\.(SM)\\.(.*)", "\\1\\-\\2\\-\\3\\-\\4\\-\\5",ciber_CUS$Mixture)
VAT <- data.frame(ciber_CUS$Mixture, ciber_CUS$`V neutrophil`)
colnames(VAT) <- c("Sample", "VAT_Neutrophil")
files_LM <- list.files(path = "../../manuscript/data/CIBERSORT/CIBERSORTx-deconvolved/GTEx", pattern = "*_LM22.csv", full.names = T)
ciber_LM <- sapply(files_LM, read_csv, simplify=FALSE) %>% bind_rows(.id = "id")
ciber_LM$Mixture <- as.factor(ciber_LM$Mixture)
ciber_LM$Mixture <- gsub("(GTEX)\\.(.*)\\.(\\d+)\\.(.*)\\.(SM)\\.(.*)", "\\1\\-\\2\\-\\3\\-\\4\\-\\5\\-\\6",ciber_LM$Mixture)
ciber_LM$Mixture <- gsub("(GTEX)\\.(.*)\\.(\\d+)\\.(SM)\\.(.*)", "\\1\\-\\2\\-\\3\\-\\4\\-\\5",ciber_LM$Mixture)
neut <- data.frame(ciber_LM$Mixture, ciber_LM$Neutrophils)
colnames(neut) <- c("Sample", "Blood_Neutrophil")
dat <- left_join(VAT,neut)
```


```{r prepare plot data}
library(tidyr)
GTEx_Portal <- read_csv("../../manuscript/data/GTEX_v8_sample-location-key.csv")
GTEx_temp <- data.frame(GTEx_Portal$SMTS,GTEx_Portal$SAMPID)
colnames(GTEx_temp) <- c("Tissue", "Sample")
ncib <- left_join(GTEx_temp,dat)

ncib <- ncib %>%
    filter(Tissue %in% c("Colon", "Spleen", "Blood", "Brain", "Liver", "Muscle", "Adipose Tissue", "Lung", "Heart", "Fallopian Tube"))

#reshape data to plot
dat_plot <- ncib %>% 
  gather("cell_type", "relative_abundance", 3:4)

#order tissue by VAT 
tiskey <- data.frame(unique(ncib$Tissue))
tiskey$med_VAT <- sapply (1:nrow(tiskey), function(i) median(ncib$VAT_Neutrophil[which(tiskey$unique.ncib.Tissue.[i] == ncib$Tissue)]))
tiskey$med_blood <- sapply (1:nrow(tiskey), function(i) median(ncib$Blood_Neutrophil[which(tiskey$unique.ncib.Tissue.[i] == ncib$Tissue)]))
tiskey$sum_VAT <- sapply (1:nrow(tiskey), function(i) sum(ncib$VAT_Neutrophil[which(tiskey$unique.ncib.Tissue.[i] == ncib$Tissue)]))
tiskey$sum_blood <- sapply (1:nrow(tiskey), function(i) sum(ncib$Blood_Neutrophil[which(tiskey$unique.ncib.Tissue.[i] == ncib$Tissue)]))
# tiskey$type <- tiskey$sum_VAT > tiskey$sum_blood
tiskey <- tiskey[order(tiskey$med_VAT),] %>%
  rename("Tissue" = "unique.ncib.Tissue.")

#reorder the level of dat_plot$Tissue to change the y axis (change based on which order y axis should be)
dat_plot$Tissue <- factor(dat_plot$Tissue, levels = tiskey$Tissue)
dat_plot <- dat_plot [!duplicated(dat_plot ),] %>%
  mutate(patnum = as.numeric(as.factor(Tissue)))
numpatkey <- dat_plot %>%
  select(Tissue, patnum)
numpatkey <- numpatkey[!duplicated(numpatkey),] %>%
  left_join(tiskey) %>%
  mutate(type = ifelse(sum_VAT > sum_blood,"VAT_Neutrophil","Blood_Neutrophil"),
         ylow = patnum - .45,
         yhigh = patnum + .45,
         xmin = 0,
         xmax = 0.75) %>%
  gather(xmin, xmax, key = "end", value = "x")
```


## Plot

```{r pressure, echo=FALSE}
library(ggplot2)
library(tidyr)

ggplot ()+
  geom_rect(data = numpatkey, mapping = aes(xmin = ylow, xmax = yhigh, ymin = 0, ymax = 1, fill=type), inherit.aes = F,show.legend = F, alpha = 0.3) +
  geom_boxplot(data = dat_plot, aes(x = as.factor(patnum), y = relative_abundance, fill = cell_type), inherit.aes = F, show.legend = T, outlier.size = 0.3)+
  scale_x_discrete(breaks = unique(numpatkey$patnum), labels = unique(numpatkey$Tissue))+
  theme(axis.text.x = element_text(size=10, angle=0))+
  theme_bw()+
  scale_fill_manual(values=c("tomato","gold"), breaks = c("Blood_Neutrophil","VAT_Neutrophil"), name = "Neutrophil Type")+
  xlab("Tissue")+
  ylab("Relative Abundance")+
  coord_flip()
 
ggsave("../figures/R01-GTEx_VAT.png", height = 3, width = 5)
```
