---
title: "R01_2023-10_nmds"
author: "Rebecca Hoyd"
date: "10/3/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(vegan)
library(viridis)
source("../../manuscript/scripts/drake-figs/R/nmds_neuts_counts.R")
```

# Functions

```{r}
pull_iso_metas <- function(){
  bldvat.meta <- readRDS("../../manuscript/data/ncbi_processed/meta_bldvat.RDS")
  sepsis.meta <- readRDS("../../manuscript/data/ncbi_processed/meta_sepsis.RDS")
  tb.meta <- readRDS("../../manuscript/data/ncbi_processed/meta_tb.RDS")
  exercise.meta <- readRDS("../../manuscript/data/ncbi_processed/meta_exercise.RDS")
  endotox.meta <- readRDS("../../manuscript/data/ncbi_processed/meta_endotox.RDS")
  syno.meta <- readRDS("../../manuscript/data/ncbi_processed/meta_syno.RDS")
  lcanc.meta <- read.csv("../../manuscript/data/ncbi_processed/meta_lung-canc.csv", stringsAsFactors = F)
  
  bldvat.meta <- bldvat.meta %>%
    mutate(sample = as.character(sample),
           source = ifelse(source == "VAT", "treatment", "control")) %>%
    arrange(sample)
  sepsis.meta <- sepsis.meta %>%
    mutate(source = ifelse(`sample_type:ch1` == "Patient", "treatment", "control")) %>%
    arrange(geo_accession) %>%
    mutate(sample = geo_accession)
  tb.meta <- tb.meta %>%
    filter(grepl("Neut", title)) %>%
    mutate(source = ifelse(grepl("Control", characteristics_ch1.3), "control", "treatment")) %>% 
    arrange(geo_accession) %>%
    mutate(sample = geo_accession)
  airspace.meta <- endotox.meta %>%
    filter(cell.type != "in vitro") %>%
    mutate(source = ifelse(cell.type == "circulating", "control", "treatment"),
           sample = as.character(sample)) %>%
    arrange(sample)
  endotox.meta <- endotox.meta %>%
    filter(cell.type == "circulating") %>%
    mutate(source = ifelse(agent == "endotoxin", "treatment", "control"),
           sample = as.character(sample)) %>%
    arrange(sample)
  exercise.meta <- exercise.meta %>%
    mutate(source = ifelse(protocol == "after exercise", "treatment", "control"),
           sample = as.character(sample)) %>%
    arrange(sample)
  syno.meta <- syno.meta %>%
    mutate(sample = as.character(sampnames),
           source = ifelse(tissue == "synovial", "treatment", "control")) %>%
    arrange(sample)
  # lcanc.meta <- lcanc.meta %>%
  #   mutate(sample = as.character(samps),
  #          source = ifelse(status == "tumor", "treatment", "control")) %>%
  #   arrange(sample)
  
  metals <- list(bldvat.meta, endotox.meta, exercise.meta, sepsis.meta, tb.meta, syno.meta, 
                 # lcanc.meta,
                 airspace.meta)
  names(metals) <- c("bldvat", "endotox", "exercise", "sepsis", "tb", "syno",
                     # "lcanc", 
                     "airspace")
  return(metals)
}

pull_iso_counts <- function(metals){
  bldvat <- read.table("../../manuscript/data/ncbi_processed/iso_bldvat.txt", 
                       sep = "\t", header = TRUE, stringsAsFactors = FALSE)
  sepsis <- read.table("../../manuscript/data/ncbi_processed/iso_sepsis.txt",
                       sep = "\t", header = TRUE, stringsAsFactors = FALSE)
  tb <- read.table("../../manuscript/data/ncbi_processed/iso_tb.txt",
                   sep = "\t", header = TRUE, stringsAsFactors = FALSE)
  exercise <- read.table("../../manuscript/data/ncbi_processed/iso_exercise.txt",
                         sep = "\t", header = TRUE, stringsAsFactors = FALSE)
  endotox <- read.table("../../manuscript/data/ncbi_processed/iso_endotox.txt",
                        sep = "\t", header = TRUE, stringsAsFactors = FALSE)
  syno <- read.table("../../manuscript/data/ncbi_processed/iso_syno_GSE116899.txt",
                     sep = "\t", header = TRUE, stringsAsFactors = FALSE)
  # lcanc <- read.table("../../data/ncbi_processed/iso_lung-canc_GSE68795.txt", 
  #                     sep = "\t", header = T, stringsAsFactors = F)
  # For this to work you're going to need to mess with the packages. But we are excluding lcanc anyway.
  # lcanc <- lcanc %>%
  #   column_to_rownames(var = "Entrez")
  # lcanc <- collapseRows(lcanc[,-1], rowGroup = lcanc$Symbol, rowID = rownames(lcanc))
  # lcanc <- lcanc$datETcollapsed %>%
  #   as.data.frame() %>%
  #   dplyr::select(lcanc.meta$sample)
  
  airspace <- endotox %>%
    gather(-Gene, key = "sample", value = "count") %>%
    mutate(count = round(count)) %>%
    spread(key = "sample", value = "count")
  
  expls <- list(bldvat, endotox, exercise, sepsis, tb, syno,
                # lcanc,
                airspace)
  datsource <- c("bldvat", "endotox", "exercise", "sepsis", "tb", "syno", 
                 # "lcanc",
                 "airspace")
  names(expls) <- datsource
  
  expls.rightsamps <- lapply(datsource, function(x) expls[[x]] %>% select(c("Gene", metals[[x]]$sample)))
  names(expls.rightsamps) <- datsource
  return(expls.rightsamps)
  
}
```

# Load data

```{r}
neutmetas <- pull_iso_metas()
neutcounts <- pull_iso_counts(neutmetas)

nmds.neuts.counts <- nmds_neuts_counts(neutcounts, neutmetas)
```

# Plot

```{r}
nmds.neuts.genes <- nmds.neuts.counts %>%
  filter(pointtype == "gene")
nmds.neuts.samples <- nmds.neuts.counts %>%
  filter(pointtype == "sample")

nmds.neuts.samples %>%
  ggplot(aes(x = MDS1, y = MDS2, color = neutgroup, fill= neutgroup,
             # label = pointlab, 
             alpha = pointtype)) +
  geom_point(data = nmds.neuts.counts, show.legend = F) +
  stat_ellipse(geom = "polygon", alpha = .3) +
  geom_point() +
  # geom_text_repel(show.legend = F) +
  scale_color_viridis(discrete = TRUE,option = "turbo", na.value = "grey66",
                      name = "Neutrophil",
                      breaks = c("airspace", "bldvat", "endotox", "exercise", "sepsis", "syno", "tb"),
                      labels = c("Airspace", "VAT", "Endotoxin", "Exercise", "Sepsis", 
                                 "Synovial", "Active TB")) +
  scale_fill_viridis(discrete = TRUE,option = "turbo", na.value = "grey66",
                      name = "Neutrophil",
                      breaks = c("airspace", "bldvat", "endotox", "exercise", "sepsis", "syno", "tb"),
                      labels = c("Airspace", "VAT", "Endotoxin", "Exercise", "Sepsis", 
                                 "Synovial", "Active TB")) +
  scale_alpha_manual(breaks = c("gene", "sample"), values = c(0.2, 1), guide = FALSE)+
  xlim(c(-1,.25)) +
  ylim(c(-.3,.5)) +
  theme_bw() 
  # theme(axis.text = element_blank(),
  #       axis.ticks = element_blank()) 

ggsave("../figures/nmds_neutrophil-state_reduce-lims.png",
       height = 5, width = 5)
```

