---
title: "SCRNA Visualizations"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(dplyr)
library(ggforce)
library(viridis)
library(tmesig)
```

# Load data

scrna.data is subset of the seurat from the paper: https://www.nature.com/articles/s41597-023-02074-6

```{r}
loadSCRNA <- function(){
  scrna.data <- readRDS("/fs/ess/PAS1695/projects/atbac/data/scRNA/scrna-seurat-subset.RDS")
  scrna.subset <- scrna.data %>%
    filter(`Cell Type` == "Neutrophils")
  return(scrna.subset)
}
```

```{r}
scrna <- loadSCRNA()
sig.genes <- read.delim("../data/custom-sig-genes_bldat.txt")
```

# Signature score

##get vat neutrophil sig genes
```{r}
neut.discrim <- sig.genes %>%
  mutate(V.enriched = V.neutrophil - Blood.neutrophil) %>%
  arrange(desc(V.enriched))

VAT.genes <- neut.discrim$NAME[1:10]
```

##format data for sig score
```{r}
scrna.frmt <- scrna %>%
  select("Sample", all_of(VAT.genes)) %>%
  column_to_rownames(var = "Sample") %>%
  t() %>%
  as.data.frame() %>%
  rownames_to_column(var = "Gene.Symbol")
```

##calculate sig score for each sample and format for umap/boxplot
```{r}
scrna.sig.score <- calculateAvgZScore(scrna.frmt, VAT.genes) %>%
  rename("sig_score" = "avg_z_score", "Sample" = "sample") %>%
  left_join(scrna[c('Sample', 'Cell Type', 'umap_1', 'umap_2')], by = "Sample")
```
# Plots

## UMAP
```{r}
summary(scrna.sig.score$sig_score)
scrna.sig.score %>%
  mutate(sig_score_2 = ifelse(sig_score > 1,1,sig_score)) %>%
  ggplot(aes(x = umap_1, y = umap_2)) + 
  geom_point(aes(colour = sig_score_2), alpha = .5) +
  labs(x = "umap 1", y = "umap 2") +
  scale_color_viridis(direction = -1, option = "A", name = "VAT Neutrophil Score") +
  theme_bw()  +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
  
ggsave("../figures/umap-scrna_neuts-only_VAT-score.png", height = 5, width = 7.5)
```
## Histogram

```{r}
scrna.sig.score %>%
  mutate(sig_score_2 = ifelse(sig_score > 1,1,sig_score)) %>%
  ggplot(aes(x = sig_score_2)) +
  geom_histogram(show.legend = F) +
  labs(title = "VAT Neutrophil Score", x = "cell type", y = "score") +
  theme_bw()  +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggsave("../figures/histogram-scrna-neut_vat.png", height = 3, width = 5)
```

## Facetting umap

```{r}
facetPlot <- function(vlike){
  tmpsplit <- scrna.sig.score %>%
    mutate(sig_score_2 = ifelse(sig_score > 1,1,sig_score),
           fcode = ifelse(sig_score > vlike, "VAT like", "Blood like")) 
  tmpsol <- scrna.sig.score %>%
    mutate(sig_score_2 = ifelse(sig_score > 1,1,sig_score),
           fcode = "All neutrophils") 
  
  p <- bind_rows(tmpsplit, tmpsol) %>%
    ggplot(aes(x = umap_1, y = umap_2)) + 
    facet_wrap(vars(fcode)) +
    geom_point(aes(colour = sig_score_2), alpha = .5) +
    labs(x = "umap 1", y = "umap 2") +
    scale_color_viridis(direction = -1, option = "A", name = "VAT Neutrophil Score") +
    theme_bw()  +
    theme(text = element_text(size = 9),
          axis.text.x = element_text(angle = 45, hjust = 1))
  
  return(p)
}
```

```{r}
vcuts <- seq(0,1,.2)

fumaps <- lapply(vcuts, facetPlot)
names(fumaps) <- vcuts

lapply(as.character(vcuts), function(x) 
  ggsave(plot = fumaps[[x]], 
         paste0("../figures/facet-umap/cutoff_", x, ".png"),
         height = 1.9, width = 7))
```
## Heatmap style

```{r}
yblocks <- range(scrna.sig.score$umap_2)
xblocks <- range(scrna.sig.score$umap_1)

pointsToBins <- function(ntiles){
  # Generate blocks
  xbreaks <- seq(xblocks[1], xblocks[2], length.out = ntiles)
  ybreaks <- seq(yblocks[1], yblocks[2], length.out = ntiles)
  
  # Assign blocks
  # median for blocks
  # Maybe n points for blocks?
  # object for plot
}
```