---
title: "SCRNA Visualizations"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(dplyr)
library(ggforce)
library(viridis)
library(tmesig)
```

##load data
```{r}
scrna.data <- readRDS("/fs/ess/PAS1695/projects/atbac/data/scRNA/scrna-seurat-subset.RDS")

cellmarker <- read.delim("/fs/ess/PAS1695/projects/atbac/data/Human_cell_markers.txt")
```

##get vat neutrophil sig genes
```{r}
neutmarkers.df <- cellmarker %>%
  filter(speciesType == "Human" & cellName == "Neutrophil" & cancerType == "Normal" & grepl("blood", tissueType, ignore.case = T))
neutmarkers.rough <- str_remove_all(unique(str_split(paste(neutmarkers.df$geneSymbol, collapse = ","), ",")[[1]]), " |\\[|\\]")
genevec <- colnames(scrna.data)
neut.hla <- genevec[grepl("HLA.DR", genevec)]

neutmarkers <- c(neutmarkers.rough[-10], neut.hla) 
```

##format data for sig score
```{r}
scrna.frmt <- scrna.data %>%
  select("Sample", all_of(neutmarkers)) %>%
  column_to_rownames(var = "Sample") %>%
  t() %>%
  as.data.frame() %>%
  rownames_to_column(var = "Gene.Symbol")
```

##calculate sig score for each sample
```{r}
##test <- scrna.frmt[1:10] %>%
  ##calculateAvgZScore(neutmarkers)

scrna.sig.score <- calculateAvgZScore(scrna.frmt, neutmarkers) %>%
  rename("sig_score" = "avg_z_score", "Sample" = "sample") %>%
  left_join(select(scrna.data, c('Cell Type', umap_1, umap_2)))
```

##make umap
```{r}
scrna.sig.score %>%
  ggplot(aes(x = umap_1, y = umap_2)) + 
  geom_point(aes(colour = sig_score)) +
  labs(x = "umap 1", y = "umap 2") +
  scale_color_viridis(direction = -1, option = "A", name = "VAT Neutrophil Score") +
  theme_bw()  +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
  
ggsave("../figures/umap-scrna-vat-neut-score.png", height = 5, width = 5)
```

##make boxplot
```{r}
scrna.sig.score %>%
  ggplot(aes(x = fct_reorder(scrna.data$`Cell Type`, sig_score), y = sig_score)) +
  geom_boxplot(show.legend = F) +
  labs(title = "VAT Neutrophil Score", x = "cell type", y = "score") +
  theme_bw()  +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggsave("../figures/box-scrna-vat-neut-score.png", height = 3, width = 5)
```
