---
title: "zymo_faux-DESeq"
output: html_document
date: '2022-11-15'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(glmm)
library(tidyverse)
library(broom)
library(rlist)
library(ggrepel)
```

# Load data

```{r}
zymo.seqtab <- read.csv("../../manuscript/data/zr8258.16S_220923.zymo/00...AllSamples.Bac16Sv34/DADA2_ASV_Distribution/ASV_Abundance_Table.csv")
zymo.tax <- read.table("../../manuscript/data/zr8258.16S_220923.zymo/00...AllSamples.Bac16Sv34/DADA2_ASV_Distribution/ASV_tax_assignments.txt", sep = "\t")
```

# Functions

```{r function for data prep}
formatTax <- function(){
  tmp <- zymo.tax %>%
    select(V1, V2) %>%
    separate(V2, into = c("kingdom", "phylum", "class", "order",
                          "family", "genus", "species"),
             sep = ";") %>%
    mutate(species = gsub("s__", "", species),
           species = paste0("s__", gsub("g__", "", genus),".", species))
  tmp$species <- make.names(tmp$species)
  return(tmp)
  
}

exoRAtowide <- function(data, taxlev){
  tmp <- data
  tmp$Taxa <- tmp[[taxlev]]
  tmp.wide<- tmp %>%
    filter(!is.na(Taxa)) %>%
    group_by(seqs, Taxa) %>%
    summarise(ra = sum(counts, na.rm = T)) %>%
    spread(key = "Taxa", value = "ra")

  return(tmp.wide)
}

exoToDF <- function(taxalevels = c("kingdom", "phylum", "class", 
                                    "order", "family", "genus", "species"), 
                     data){
  w.ls <- lapply(taxalevels, function(x) exoRAtowide(data, x))
  w.df <- reduce(w.ls, function(x,y) left_join(x,y)) 
  return(w.df)
}

formatModelData <- function(){
  tax <- formatTax()
  dessamps <- zymo.seqtab %>%
    filter(grepl("HFD.VAT", seqs) & !grepl("Saline", seqs))
  all0 <- names(subset(colSums(dessamps[,-1]), colSums(dessamps[,-1]) == 0))
  
  desseqs <- dessamps %>%
    select(-all0) %>%
    pivot_longer(-seqs, names_to = "V1", values_to = "counts") %>%
    left_join(tax)
  
  desseqs.w <- exoToDF(data = desseqs)
  return(desseqs.w)
}
```

```{r functions for analysis}
capture.models.univ <- function(outcome, lfun, modin, mics){
  mods.list <- lapply(mics, function(x) try({glm(as.formula(paste0(outcome, " ~ `", x, "`")), family = Gamma, data = modin) %>%
                        tidy()})
                      )
                      
  mods.list.clean <- list.clean(mods.list, function(x) is.null(x))
  mods.df <- bind_rows(mods.list.clean)
  return(mods.df)
}

calculatePValues <- function(){
  moddat <- formatModelData()
  microbes <- colnames(moddat[,-1])
  
  moddat.lab <- moddat %>%
    mutate(ob.lean = ifelse(grepl("Lean", seqs), 1,2))
  
  mod.pvals <- capture.models.univ("ob.lean", "gamma", moddat.lab, microbes) %>%
    filter(term != "(Intercept)") %>%
    select(term, p.value)
  
  return(mod.pvals)
  
}

calculateFoldChange <- function(){
  moddat <- formatModelData()
  
  foldcalc <- moddat %>%
    pivot_longer(-seqs, names_to = "microbes", values_to = "counts") %>%
    mutate(gavage = gsub("gavage.*", "", seqs)) %>%
    group_by(gavage, microbes) %>%
    summarise(gmean = mean(counts)) %>%
    pivot_wider(names_from = "gavage", values_from = gmean) %>%
    mutate(log2foldchange = log(Obese/Lean, base = 2)) %>%
    rename("term" = "microbes") %>%
    select(term, log2foldchange)
  
  return(foldcalc)
}

volcanoPlotDat <- function(){
  pvals <- calculatePValues()
  fold <- calculateFoldChange()
  
  plotin <- pvals %>%
    left_join(fold) %>%
    mutate(taxlev = ifelse(p.value < 0.05, str_sub(term, 1, 1), NA),
           textlab = ifelse(p.value < 0.05, term, NA),
           inf.rescale = ifelse(log2foldchange == Inf, 10,
                                ifelse(log2foldchange == -Inf, -10, log2foldchange)))
  
  return(plotin)
}

# foundInStool <- function(){
#   tax <- formatTax()
#   
#   dessamps <- zymo.seqtab %>%
#     filter(grepl("gavage$", seqs))
#   all0 <- names(subset(colSums(dessamps[,-1]), colSums(dessamps[,-1]) == 0))
#   
#   desseqs <- dessamps %>%
#     select(-all0) %>%
#     pivot_longer(-seqs, names_to = "V1", values_to = "counts") %>%
#     left_join(tax)
#   
#   desseqs.w <- exoToDF(data = desseqs)
#   
#   desseqs.l <- desseqs.w %>%
#     column_to_rownames(var = "seqs") %>%
#     t() %>%
#     as.data.frame() %>%
#     rownames_to_column(var = "microbe") %>%
#     mutate(found.in.Lean = ifelse(Leangavage > 0, 1, 0),
#            found.in.Obese = ifelse(Obesegavage > 1,1,0)) %>%
#     select(microbe, contains("found.in"))
#   
#   return(desseqs.l)
# }
```


# Visuals

```{r}
volplot <- volcanoPlotDat()
foundin <- foundInStool() %>%
  mutate(term = microbe)

volplot %>%
  filter(!inf.rescale %in% c(-10,10) & !is.na(inf.rescale)) %>%
  filter(!term %in% c("f__NA", "g__NA")) %>%
  # mutate(textlab = ifelse(grepl("s__NA.sp", textlab), "", textlab),
  #        textlab = ifelse(abs(log2foldchange) > 2.5, textlab, NA),
  #        textlab = ifelse(textlab %in% c("g__Akkermansia", 
  #                                        "f__Verrucomicrobiaceae",
  #                                        "o__Verrucomicrobiales",
  #                                        "c__Verrucomicrobiae",
  #                                        "p__Verrucomicrobia"),
  #                         NA,
  #                         textlab)
  #        ) %>%
  # left_join(foundin) %>%
  # mutate(found.in.Obese = as.character(replace_na(found.in.Obese, 0)),
  #        found.in.Lean = as.character(replace_na(found.in.Lean, 0)),
  #        foundin.code = case_when(found.in.Obese ==1 & found.in.Lean == 1 ~ "Both",
  #                                 found.in.Obese == 1 & found.in.Lean == 0 ~ "Obese",
  #                                 found.in.Obese ==0 & found.in.Lean == 1~ "Lean",
  #                                 found.in.Obese ==0 & found.in.Lean == 0 ~ "Neither")) %>%
  ggplot(aes(x = inf.rescale, y = -log(p.value), color = taxlev, label = textlab)) +
  geom_point() +
  geom_vline(xintercept = 0, lty = 2) +
  geom_text_repel(max.overlaps = 20, show.legend = F) +
  geom_hline(yintercept = -log(0.05), lty = 2) +
  labs(x = "Log2FoldChange") +
  scale_color_brewer(palette = "Dark2", na.value = "grey") +
  # xlim(c(-10,10)) +
  theme_bw() +
  theme(text = element_text(size = 8))

ggsave("../figures/volcano_HFD_Obese-Lean_VAT.png")
```

# Table

```{r}
pval.table <- volplot %>%
  mutate(term = gsub("`", "", term)) %>%
  select(-taxlev, -textlab, -inf.rescale) %>%
  rename("microbe" = "term")

miccounts <- formatModelData()
micmeans <- miccounts %>%
  pivot_longer(-seqs, names_to = "microbe", values_to = "counts") %>%
  mutate(gavage = paste0("mean.", gsub("gavage.*", "", seqs))) %>%
  group_by(gavage, microbe) %>%
  summarise(gmean = mean(counts)) %>%
  pivot_wider(names_from = "gavage", values_from = gmean) %>%
  left_join(pval.table)

write.csv(micmeans, "../tables/HFD-stool_pvals_VAT.csv", row.names = F)
```

